### ISSUE TITLE
请完善使用说明，需要安装一些不常用的package

### ISSUE THREAD

**Issue by ai2ming** [xuliangzhan/vue-element-extends#1]
使用说明比较简单，只是说使用Editable.vue 和 EditableColumn.vue两个文件
经测试除了常用的elementUI、vuex之外，还需要安装其他package，具体如下：

npm install node-sass sass-loader -D
npm install xe-utils --S

另外，为了简化安装，EditableColumn.vue中可以考虑不用sass的语法，我看没用sass什么特别的功能，和直接写css差别不大。

**Comment by xuliangzhan** [comment]
多谢你的建议，已移除 sass 依赖，只需依赖 xe-utils 和 vuex，为了减少依赖库也可以自行替换 xe-utils 为项目中所使用的函数库。

现依赖如下：
npm install vuex xe-utils
需要依赖 vuex 中的一个属性 globalClick (具体实现方式可以参考store/modules/event.js)
然后只需将 Editable.vue 和 EditableColumn.vue 两个组件复制到自己项目中就行。
