### ISSUE TITLE
请问如何放弃更改（取消修改）某一行的数据？

### ISSUE THREAD

**Issue by xlkit456852** [xuliangzhan/vue-element-extends#10]
在demo中只发现了revert()方法放弃整个table的修改，如果想放弃修改某一行的数据应该如何处理？感谢指导

**Comment by xuliangzhan** [comment]
可以支持还原行数据，传参数 row 即可， this.$refs.editable.revert(row)

**Comment by xlkit456852** [comment]
谢谢，成功了，非常好用(*^▽^*)
