### ISSUE TITLE
行校验+弹出dialog

### ISSUE THREAD

**Issue by xiangli82** [xuliangzhan/vue-element-extends#101]
**问题描述 Describe the bug**
行校验提示错误后弹出dialog,错误信息会在显示在dialog上面

**重现问题的步骤 To Reproduce**
最新版本校验行数据,提示错误信息,点及其他地方显示dialog, 再点击空白处,校验的错误信息显示在dialog上
请问,我想校验信息不在dialog上面显示怎么弄啊?

**报错信息或截图 Error message or screenshots**
![image](https://user-images.githubusercontent.com/40375825/57513933-f448f000-7341-11e9-8872-169f52a30d3f.png)
![image](https://user-images.githubusercontent.com/40375825/57513984-0f1b6480-7342-11e9-987c-d5ff4d0df46c.png)

**Comment by xuliangzhan** [comment]
将 useDefaultValidTip: true 参数加上试试

**Comment by xiangli82** [comment]
> 将 useDefaultValidTip: true 参数加上试试

我看api这个参数默认是true,不行,改成false后也不行

**Comment by xixinglong** [comment]
你可以在关闭弹窗关闭时调用钩子函数触发  refresh revert 方法 ，可以间接性解决 错误信息会在显示在dialog上面
