### ISSUE TITLE
edit-table可以在input或者select里面添加回车事件吗

### ISSUE THREAD

**Issue by tushuyuehou** [xuliangzhan/vue-element-extends#105]
**描述 Describe**
edit-table可以在input或者select里面添加回车事件吗？

**Comment by xuliangzhan** [comment]
只要组件支持，该怎么加都可以加，一样的，自定义模板或者 :edit-render="{name:'',evnts:{},props:{}}"

**Comment by xuliangzhan** [comment]
事件可以参考这个 #104
