### ISSUE TITLE
 在使用ElSelect的时候 加了一个multiple多选属性 报Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by mklm305** [xuliangzhan/vue-element-extends#106]
**描述 Describe**
 在使用ElSelect的时候 加了一个multiple多选属性 报Cannot read property 'indexOf' of null

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**请填写以下版本信息 please complete the following information**
vue: 2.6.10
element-ui: 2.4
vue-element-extends: 1.2.15

**Comment by xuliangzhan** [comment]
你应该提供相关代码或链接，提供信息太少

**Comment by lnlnln123** [comment]
我也遇到了同样的问题，请问你是如何解决的？

**Comment by hhwsgit** [comment]
ElSelect使用多选解决了吗

**Comment by lnlnln123** [comment]
是可以多选的，只不过多选的时候第一次点击没有选择值，报错，第二次点击的时候正常

**Comment by xuliangzhan** [comment]
这种情况你应该检查数据，多选的值是数组，非数组报错是必然的  [demo](https://xuliangzhan.github.io/vue-element-extends/#/editable/click9)
