### ISSUE TITLE
分页多选

### ISSUE THREAD

**Issue by JimboXie** [xuliangzhan/vue-element-extends#107]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**
数据分页的情况下，我选择第一页的某些数据，然后切换到第二页，选某些数据，点击确定的时候获取第一页的数据和第二页的数据。

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**
类似于avue中的avue-crud组件的tableSelect

**是否有不错的替代方案 Describe alternatives you've considered**
类似于avue中的avue-crud组件的tableSelect

**Comment by xuliangzhan** [comment]
你可以在勾选事件中把值记录下来

**Comment by xuliangzhan** [comment]
https://xuliangzhan_admin.gitee.io/vxe-table/#/table/advanced/page
