### ISSUE TITLE
当滚动加载时，renderSize设置为100，但是数据量超过100条，此时对数据排序不是完整的数据

### ISSUE THREAD

**Issue by breezefeng** [xuliangzhan/vue-element-extends#108]

**Comment by xuliangzhan** [comment]
由于是基于 element 封装的，这个涉及内部数据不好处理
如果需要这个功能可以看下这个表格可以支持 [vxe-table](https://xuliangzhan.github.io/vxe-table/#/table/scroll/scroll)

**Comment by breezefeng** [comment]
使用vxe-table跟element-ui交互体验不一致，希望能解决这个bug

**Comment by breezefeng** [comment]
可以加qq一起探讨下吗？我的qq：1024597165

**Comment by xuliangzhan** [comment]
是什么问题？

**Comment by xuliangzhan** [comment]
完整的建议用这个 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/base/basic
