### ISSUE TITLE
新增记录按取消操作后，原本第一条记录的show-overflow-tooltip会失效

### ISSUE THREAD

**Issue by owen4comes** [xuliangzhan/vue-element-extends#109]
**问题描述 Describe the bug**
如题目

**重现问题的步骤 To Reproduce**
新增一条记录（新增在第一行）
进行取消操作-》移除数据
原第一行的show-overflow-tooltip单元格会失去这个效果，看源码是加上了disabled-el-tooltip类，但不知道为什么会加上这个类

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**
在demo的manual4中可以重现，将manual4中第一列的show-overflow-tooltip单元格多谢点数据，达到超出效果，然后进行上面的重现问题步骤

**报错信息或截图 Error message or screenshots**
无

**期望的结果 Expected behavior**
新增的取消操作不影响其他行的show-overflow-tooltips效果

**请填写以下版本信息 please complete the following information**
 - vue: 2.6.10
 - element-ui: 2.8.2
 - vue-element-extends: 1.2.14

**Comment by xuliangzhan** [comment]
你可以更新到最新试下
