### ISSUE TITLE
自定义校验问题

### ISSUE THREAD

**Issue by xiangli82** [xuliangzhan/vue-element-extends#110]
**描述 Describe**
只添加自定义校验的时候,有值才会触发校验的方法,没有值就不会去触发,并且没有值的时候就算调用validate方法也不能触发自定义校验.

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**
![image](https://user-images.githubusercontent.com/40375825/57839235-e3442700-77f8-11e9-9f22-b2a90172c7c1.png)
![image](https://user-images.githubusercontent.com/40375825/57839272-f5be6080-77f8-11e9-80c9-3bb56a9f16d6.png)
![image](https://user-images.githubusercontent.com/40375825/57839292-05d64000-77f9-11e9-920f-ac281712cedb.png)
![image](https://user-images.githubusercontent.com/40375825/57839511-72513f00-77f9-11e9-860f-1f548271af7f.png)

**请填写以下版本信息 please complete the following information**
vue: ?
element-ui: ?
vue-element-extends: ?

**Comment by xuliangzhan** [comment]
你可以更新到最新试下

**Comment by xiangli82** [comment]
> 你可以更新到最新试下

谢谢大佬,解决了
