### ISSUE TITLE
使用elem表格原来的方法setCurrentRow()报错

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vue-element-extends#112]
**问题描述 Describe the bug**

需要设置高亮行，传入row之后报错
**重现问题的步骤 To Reproduce**

在updated中调用setCurrentRow（）方法
下面是我的代码
![image](https://user-images.githubusercontent.com/30314164/57901415-a54a1000-7897-11e9-9b8d-c4f1b2270342.png)

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**报错信息或截图 Error message or screenshots**

![image](https://user-images.githubusercontent.com/30314164/57900891-48e5f100-7895-11e9-9475-ae8bfdfbd794.png)

![image](https://user-images.githubusercontent.com/30314164/57901000-b134d280-7895-11e9-81e9-214419e27b7f.png)

**期望的结果 Expected behavior**

调用成功，设置高亮行
**请填写以下版本信息 please complete the following information**
 -     "vue": "^2.5.21",
 -     "element-ui": "^2.8.2",
 -  "vue-element-extends": "^1.2.16",

**Comment by xuliangzhan** [comment]
这个 currentRow 相关参数打印看下

**Comment by wekerSnail** [comment]
周末没法跑代码，不过参数我记得，是我点击的表格那行的数据参数，大致这个样子｛name:'',id:'',...｝

**Comment by wekerSnail** [comment]
![image](https://user-images.githubusercontent.com/30314164/58001049-fb73b900-7b0c-11e9-9477-f9bab8ee086a.png)
我在下拉菜单选择完，那选择的结果去查询一个值，在设置当前编辑行的数据，通关reloadRow(row)方法重置当前行的数据，但是没有效果，数据并没有变

row打印出来是这样的
![image](https://user-images.githubusercontent.com/30314164/58001262-98ceed00-7b0d-11e9-88aa-389d57d5c630.png)

**Comment by wekerSnail** [comment]
貌似搞清楚了，数据得保持引用关系，使用接收值修改属性在传入，不能使用新变量去传入
