### ISSUE TITLE
remove如何删除新增的行？

### ISSUE THREAD

**Issue by owen4comes** [xuliangzhan/vue-element-extends#113]
**描述 Describe**
在某行下新增多行数据，但用remove无法删除这几行新增的数据。是不是传入remove的row参数不正确呢？

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**
http://jsrun.net/8hyKp/edit

**请填写以下版本信息 please complete the following information**
vue: 2.6.10
element-ui: 2.8.2
vue-element-extends:1.2.14

**Comment by xuliangzhan** [comment]
你传的不是 row 并非行数据，必须是指定 tableData 中的 row

**Comment by owen4comes** [comment]
那就是说我的新增的行必须放到tableData里，这样才能识别出行数据，不能放在tableData->item->children里面？

**Comment by owen4comes** [comment]
其实之前能用index去insert和remove是更方便的，因为有时需要点击当前行，但insert或者remove的是当前行的下一行或者下几行，这时候用index就比较方便，可以获取当前行scope.$index再+n就可以操作对应行，但现在方法需要传row的话，就不知道怎样获取当前行的下一行或者下几行的scope.row了

**Comment by xuliangzhan** [comment]
数据放哪里都可以，但入参必须从data中取
