### ISSUE TITLE
表格列的ElSelect没有搜索功能，用filterable不起作用

### ISSUE THREAD

**Issue by herogui** [xuliangzhan/vue-element-extends#114]
**问题描述 Describe the bug**

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - vue: ?
 - element-ui: ?
 - vue-element-extends: ?

**Comment by xuliangzhan** [comment]
相关参数参考这个 #104
