### ISSUE TITLE
表头宽度和表格宽度不一致，导致表头最后有一块空白

### ISSUE THREAD

**Issue by flywin8** [xuliangzhan/vue-element-extends#115]
**问题描述 Describe the bug**
表头宽度和表格宽度不一致，导致表头最后有一块空白

**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**
https://xuliangzhan.github.io/vue-element-extends/#/editable/click5

**报错信息或截图 Error message or screenshots**
![image](https://user-images.githubusercontent.com/13073744/58142196-b7052c00-7c78-11e9-9612-ce3611d638e4.png)

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - vue: 2.6.6
 - element-ui: 2.4.6
 - vue-element-extends: 1.2.19

**Comment by xuliangzhan** [comment]
这个你更新 element 看下
