### ISSUE TITLE
必输校验时必须输入值才能填写其他列信息（mode: 'cell'时）

### ISSUE THREAD

**Issue by z-Xiaode** [xuliangzhan/vue-element-extends#117]
**问题描述 Describe the bug**
必输校验时必须输入值才能填写其他列信息（mode: 'cell'时）

**重现问题的步骤 To Reproduce**
A列和B列都是必输，输入B列的值时校验提示必须A列有值才能输入，但是B列必输校验控制住了，不能到A列输入值

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**
当输入列为必输时，可以先输入其他列的值

**请填写以下版本信息 please complete the following information**
 - vue: ^2.6.6
 - element-ui: 2.8.2
 - vue-element-extends: 1.2.19

**Comment by xixinglong** [comment]
对的，我也遇到这个问题了，希望可以修复这个问题

**Comment by xuliangzhan** [comment]
具体怎么重现的？

**Comment by z-Xiaode** [comment]
> 具体怎么重现的？
click9   新增=》点击聚焦到名称 =》（名称不输入）切换聚焦到其他列输入数据
![image](https://user-images.githubusercontent.com/49858032/58391346-193ea200-8068-11e9-9bbf-222c21a9622e.png)

**Comment by xixinglong** [comment]
我遇到的问题是 行编辑加校验   新增一行后， 校验提示弹出，这时点击其他行或单元格无效，必须满足当前单元格或行校验规则后，才可以编辑其他单元格或行，  照道理讲，当前行不符合校验规则，但是我仍然可以编辑其它单元格或行呀，这就是问题所在，效果如实例  双击模式 行编辑 + 校验  新增编辑
期望效果：可以实时校验或者点击提交后统一校验
![image](https://user-images.githubusercontent.com/25213883/58449463-39409500-813e-11e9-9d9b-8e1aab1cd107.png)

**Comment by z-Xiaode** [comment]
> 我遇到的问题是 行编辑加校验 新增一行后， 校验提示弹出，这时点击其他行或单元格无效，必须满足当前单元格或行校验规则后，才可以编辑其他单元格或行， 照道理讲，当前行不符合校验规则，但是我仍然可以编辑其它单元格或行呀，这就是问题所在，效果如实例 双击模式 行编辑 + 校验 新增编辑
> 期望效果：可以实时校验或者点击提交后统一校验
> ![image](https://user-images.githubusercontent.com/25213883/58449463-39409500-813e-11e9-9d9b-8e1aab1cd107.png)

我自己找了两种方案(间接性解决)：
1、采用mode:'row'  ,打开整行编辑，能满足大部分需求，但是无法编辑其他行
2、绑定一个事件，不满足校验时调用clearActive()方法可清除编辑状态，此时可编辑其他列

**Comment by xuliangzhan** [comment]
这个可能不会那么快解决，你可以参考这个 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/cellValid
