### ISSUE TITLE
ElSelect加上event的change事件相关校验的问题

### ISSUE THREAD

**Issue by xiangli82** [xuliangzhan/vue-element-extends#118]
**描述 Describe**
change触发必输校验信息的ElSelect,加上一个change事件.
在已经触发了必输校验,并显示错误信息后,再选择select值,错误信息不会自动消失.
请问这中情况是我哪里写错了吗?

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**
<elx-editable-column prop="pkFiles" label="维度" :edit-render="{name: 'ElSelect', options: pkFilesOptions,
        optionProps: {value: 'id', label: 'filesName'}, events:{change: onPkFilesChange}}">
      </elx-editable-column>

pkFiles:[
          {required: true, message: '请选择维度', trigger: 'change'}
        ],

**请填写以下版本信息 please complete the following information**
vue: ?
element-ui: ?
vue-element-extends: ?

**Comment by xuliangzhan** [comment]
如果使用了默认的 change 事件，需要手动调用 updateStatus 方法刷新状态
