### ISSUE TITLE
自定义校验参数能否加上当前行数据

### ISSUE THREAD

**Issue by xiangli82** [xuliangzhan/vue-element-extends#119]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**
你好，请问一下我自定义检验的时候怎么获取检验的行数据呢？现在我是用单击单元格编辑，因为业务需要通过校验的行里面其他数据进行自定义检验，可不可以在自定义检验传的参数里面多加一个行数据，或者index？

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by xuliangzhan** [comment]
你可以更新到最新，可以支持 validator(rule, value, callback, {row, column}
