### ISSUE TITLE
是否可禁用 “当点击其它地方后，自动清除最后活动列”

### ISSUE THREAD

**Issue by xlkit456852** [xuliangzhan/vue-element-extends#12]
触发方式：manual 手动触发模式
编辑方式：row  行编辑模式

在开发时发现，编辑某行的某几列数据后，点击其他地方，这行数据会直接成为表格新的一行，貌似也没有根据文档中“当点击其它地方后，自动清除最后活动列”这样操作，也没有调用保存方法。
于是我去文档找到clear-active事件，使用后发现：这行数据直接成为表格新的一行后才调用这个事件绑定的方法，但希望能做到的是：
（1）在这行数据成为表格新的一行前，我可以截断它，这条数据仍保持在编辑状态：比如弹出一个confirm框，咨询用户接下来是想保存这行数据还是继续编辑还是放弃更改这行数据。
（2）或者直接禁用这个点击其他地方对正在编辑行的影响。

感谢解答Thanks♪(･ω･)ﾉ

**Comment by xuliangzhan** [comment]
增加配置 autoClearActive 支持关闭自动清除最后活动编辑
请参考这个 [demo](https://xuliangzhan.github.io/vue-element-extends/#/editable/manual3)

**Comment by xlkit456852** [comment]
OK，已成功，谢谢！另外还想问一下，当编辑行保存后，如何将这次修改作为最新的修改？如果没有这个操作，那下次再修改本行时，如果做revert操作，将会又回到本行最初的版本

**Comment by xuliangzhan** [comment]
在异步保存之后调用 this.$refs.editable.reloadRow(row) 就可以重新初始化行数据

**Comment by xlkit456852** [comment]
明白，谢谢~
