### ISSUE TITLE
行编辑的时候props希望可以传对象的一个属性，然后编辑完的回调参数row包含这个对象的多有属性

### ISSUE THREAD

**Issue by samluby** [xuliangzhan/vue-element-extends#120]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by xuliangzhan** [comment]
不太清楚你指的是哪里参数
