### ISSUE TITLE
同时使用了fixed列和数据校验的问题

### ISSUE THREAD

**Issue by zerozrn** [xuliangzhan/vue-element-extends#125]
使用了fixed列和数据校验，tooltip会生成多个；设置useDefaultValidTip为true后，解决了tooltip问题，但是我自定义的popover闪现消失
![QQ截图20190530114746](https://user-images.githubusercontent.com/19562124/58607099-d29fb080-82d0-11e9-84ce-40bb176eb9cb.png)
![QQ图片20190530115007](https://user-images.githubusercontent.com/19562124/58607158-0d094d80-82d1-11e9-9794-03e627b92b73.png)

element-ui: 2.4.11
vue-element-extends: 1.2.15

**Comment by xuliangzhan** [comment]
由于 element 的实现方式是浮动列也是独立的一个 table ，所以会造成多个渲染，目前只有使用 useDefaultValidTip: true，使用 useDefaultValidTip 也有个缺点就是提示会被表格超出隐藏，所以至少需要设置两行以上高度

**Comment by zerozrn** [comment]
好吧，没有办法了，只能有所舍弃
感谢大大及时回复

**Comment by xuliangzhan** [comment]
这个功能新表格可以解决 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/cellValid
