### ISSUE TITLE
请将问题描述清楚、并提供相关报错信息，否则可能不会及时帮你解决！！！

### ISSUE THREAD

**Issue by sunday9528** [xuliangzhan/vue-element-extends#127]
**问题描述 Describe the bug**
树形表格
因为项目原因，不想一行一行编辑，希望点击编辑，所以 :edit-config="{trigger: 'click', mode: 'cell'}"
树形表格单击编辑，顶级行编辑Ok,次级行编辑报错，git下来 ，源码同样报错，
报错位置：$refs.elxEditable.updateStatus(scope)，中_getColumnByRowIndex方法
看源码后，猜测可能是因为树形结构数据找不到rowIndex，此问题也仅在树形表格单击绑定数据中发现
虽然数据更新了，但是看着一片一片红，真心难受，

**报错信息或截图 Error message or screenshots**
vue.runtime.esm.js?6e6d:619 [Vue warn]: Error in v-on handler (Promise/async): "TypeError: Cannot read property 'querySelector' of undefined"

found in

---> <ElInput> at packages/input/src/input.vue
       <ElTableBody>
         <ElTable> at packages/table/src/table.vue
           <ElxEditable> at packages/editable/src/editable.vue
             <Manual6> at examples/views/editable/Manual6.vue
               <App> at examples/App.vue
                 <Root>

**请填写以下版本信息 please complete the following information**
 - vue: 2.6.10
 - element-ui: 2.9.1
 - vue-element-extends: 1.2.20

**Comment by xuliangzhan** [comment]
树只能支持小部分功能，不知道你的是什么场景，[基础](https://xuliangzhan.github.io/vue-element-extends/#/editable/dblclick7)的编辑是可以支持的

**Comment by sunday9528** [comment]
树的children行 cell 模式，编辑时调用updateStatus 方法，
方法：  const { row, cell } = this._getColumnByRowIndex(record, column.property)
在此方法中   const cell = trElem.querySelector(`.${column.id}`) 出错，
因为树结构数据无法返回正确的row，
所以会导致节点选择报错，但最终值还是修改成功，
源码位置：editbale.vue =>updateStatus=>_getColumnByRowIndex=>trElem.querySelector
重现：树形表格 只需要修改 :edit-config="{trigger: 'click', mode: 'cell',} 然后编辑childen行数据 即可重现
在此非常感谢你的组件，因为项目中有大量表格编辑，你的组件对我大有帮助，非常感谢，同时也希望你的组件越做越好，有越来越多的人使用。

**Comment by xuliangzhan** [comment]
这个就是 [https://xuliangzhan.github.io/vue-element-extends/#/editable/dblclick7](https://xuliangzhan.github.io/vue-element-extends/#/editable/dblclick7)，没发现增删改查会报错

**Comment by sunday9528** [comment]
确实没有问题，可能是我配置错误，我再查查，
我使用的是https://xuliangzhan.github.io/vue-element-extends/#/editable/manual6
然后修改     :edit-config="{trigger: 'click', mode: 'cell'}"
然后在编辑children  时 报的错，以上是我再源码中修改出现的问题
![image](https://user-images.githubusercontent.com/22463448/58746326-b138f300-848f-11e9-934d-ecbff09c3c44.png)
![image](https://user-images.githubusercontent.com/22463448/58746331-c6ae1d00-848f-11e9-90dc-8dc64b1bb1d9.png)

**Comment by sunday9528** [comment]
在https://xuliangzhan.github.io/vue-element-extends/#/editable/dblclick7 中 我同样修改

![image](https://user-images.githubusercontent.com/22463448/58746368-1260c680-8490-11e9-80c7-934d1a81a0a1.png)
也出现此问题
![image](https://user-images.githubusercontent.com/22463448/58746364-0aa12200-8490-11e9-9d35-8a45e3312653.png)

**Comment by xuliangzhan** [comment]
你重新拉取源码再 demo 跑下，我没发现有报这个错

**Comment by sunday9528** [comment]
😂
![image](https://user-images.githubusercontent.com/22463448/58746595-78e6e400-8492-11e9-8868-2d6bff92acac.png)
没事的，我这边重写了你的方法，临时解决的这个问题
![image](https://user-images.githubusercontent.com/22463448/58746626-cf542280-8492-11e9-8962-319a604e4be2.png)

**Comment by xuliangzhan** [comment]
看你是用了 element 的 treeProps:{} ？这个目前不兼容哈，目前只兼容 :edit-config="{prop:{}}"

**Comment by sunday9528** [comment]
我这边 是在源码基础上改的
![image](https://user-images.githubusercontent.com/22463448/58746753-7b4a3d80-8494-11e9-9110-529f9f4e4706.png)
而且发现右键菜单也出现问题了😂,经常失效
![image](https://user-images.githubusercontent.com/22463448/58746778-ccf2c800-8494-11e9-9575-6a2ed389da53.png)

**Comment by xuliangzhan** [comment]
树除了基础的增删改查，其他可能会存在问题的，这个结构不一样，这个涉及内部数据很多情况是不好处理的 哈

**Comment by sunday9528** [comment]
是的,我发现你的代码中很多地方都是直接取TableData 数据 ,如果是TreeData  就可能会出问题,
![image](https://user-images.githubusercontent.com/22463448/58746884-332c1a80-8496-11e9-81bc-74673793e5b0.png)
不管怎样哈，都非常感谢你开发这么优秀的组件👍😊

**Comment by xuliangzhan** [comment]
这种树的 vxe-table 才能支持所有功能，基于 element 二次封装的这个目前是支持不了 很多限制的 哈

**Comment by ggzzddd** [comment]
> 是的,我发现你的代码中很多地方都是直接取TableData 数据 ,如果是TreeData 就可能会出问题,
> ![image](https://user-images.githubusercontent.com/22463448/58746884-332c1a80-8496-11e9-81bc-74673793e5b0.png)
> 不管怎样哈，都非常感谢你开发这么优秀的组件



> 你重新拉取源码再 demo 跑下，我没发现有报这个错

从master拉去代码
```
yarn
npm run serve
```
![image](https://user-images.githubusercontent.com/40220868/59323347-e6a1d400-8d0c-11e9-98b7-c7f84305a1e9.png)
