### ISSUE TITLE
表格的校验规则能每一行都不一样吗？

### ISSUE THREAD

**Issue by tushuyuehou** [xuliangzhan/vue-element-extends#128]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**
表格的校验规则能每一行都不一样吗？

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**
例如：第一行数据我要校验name不为空，不校验sex，第二行要校验name，sex不能为空，还有在提交时
self.$refs['elxEditable'].validate()怎样实现不同行的校验

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by xuliangzhan** [comment]
这个你用自定义校验就可以自行处理

**Comment by zongwong** [comment]
请问一下 自定义校验 数组对象 为什么change 不实时触发?
