### ISSUE TITLE
异步获取列表数据，不会自动更新，需要调用reload()

### ISSUE THREAD

**Issue by xlkit456852** [xuliangzhan/vue-element-extends#13]
在mounted()中获取异步数据，获得数据后赋值给data，但发现数据在el-editable是有的，但是传不进去el-table里，然后我再reload(data)一下就可以看到数据了，请问这是正常的吗？

**Comment by xuliangzhan** [comment]
该 bug 已修复了，请获取最新组件及更新依赖

**Comment by 3xxx** [comment]
和我昨天提的是一样的吧：发现不能从服务端更新数据，使用的是data()里return的数据，mounted从服务端取到的数据没有显示出来。

**Comment by xuliangzhan** [comment]
是的，但是对于增删数据还是建议使用函数 insert()、remove()，其他都可以直接操作 data

**Comment by 3xxx** [comment]
可以了。感谢，可以愉快地玩耍了。

**Comment by xlkit456852** [comment]
谢谢~非常棒！
