### ISSUE TITLE
请教关于 InputNumber 最大值设定为当前单元格值的问题

### ISSUE THREAD

**Issue by yixiu025** [xuliangzhan/vue-element-extends#130]
**描述 Describe**
由于项目中需要控制编辑时，修改后的值不允许大于原始值。
所以请教下 配置edit-render 为InputNumber时，如何根据当前单元格的值为InputNumber max属性。

**请填写以下版本信息 please complete the following information**
vue: 2.5.2
element-ui: 2.8.2
vue-element-extends: 1.2.19

**Comment by xuliangzhan** [comment]
使用自定义模板就行
