### ISSUE TITLE
整表一起编辑

### ISSUE THREAD

**Issue by zerozrn** [xuliangzhan/vue-element-extends#131]
项目需要整表编辑，点击页面上编辑按钮，表的每一行都变成编辑状态，当编辑好每一行数据后，一起保存。请问如何实现整表编辑呢？

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**请填写以下版本信息 please complete the following information**
vue: 2.5.2
element-ui: 2.4
vue-element-extends: 1.2.15

**Comment by xuliangzhan** [comment]
如果是全部为编辑状态，我觉得这个你使用 el-table 和自定义模板实现还更简单些
