### ISSUE TITLE
编辑表格使用下拉框change时如何将旁边的下拉框默认值置空

### ISSUE THREAD

**Issue by Codezero123** [xuliangzhan/vue-element-extends#132]
**描述 Describe**
请帮忙看一下如何操作
![image](https://user-images.githubusercontent.com/28008514/58937625-8b6c6080-87a5-11e9-9678-74893d215f96.png)

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**请填写以下版本信息 please complete the following information**
vue: ?
element-ui: ?
vue-element-extends: ?

**Comment by Dadshuai** [comment]
你已经解决这个问题了吗

**Comment by Codezero123** [comment]
嗯是的，切换的时候把对应的scope.row.你需要清空的东西清掉就行
