### ISSUE TITLE
自定义渲染时，打开编辑输入时报错

### ISSUE THREAD

**Issue by z-Xiaode** [xuliangzhan/vue-element-extends#135]
**描述 Describe**
![image](https://user-images.githubusercontent.com/49858032/59018424-70b6ec00-8878-11e9-874c-c0b21d020b2a.png)
我定位不到问题，希望能得到帮助

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**请填写以下版本信息 please complete the following information**
vue: ?
element-ui: ?
vue-element-extends: ?

**Comment by orange0606** [comment]
我也是遇到这种问题
