### ISSUE TITLE
数据刷新，表格全选按钮保持半选状态

### ISSUE THREAD

**Issue by GlenHeart** [xuliangzhan/vue-element-extends#137]
**问题描述 Describe the bug**
数据刷新，表格全选按钮保持半选状态

**重现问题的步骤 To Reproduce**
选择部分数据，提交后，表头全选按钮保持了之前的状态

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - vue: ?
 - element-ui: ?
 - vue-element-extends: ?

**Comment by xuliangzhan** [comment]
这个你可以调方法 clearSelection 清除

**Comment by GlenHeart** [comment]
我自己是强制刷新组件的解决的，谢谢
