### ISSUE TITLE
insert()行后马上setActiveRow失败

### ISSUE THREAD

**Issue by xlkit456852** [xuliangzhan/vue-element-extends#14]
demo的新增数据操作是点击新增一行，然后需要手动点击新增行的编辑才能编辑该行数据，我为了提高用户体验，在点击新增按钮时，除了insert新行还将其设为当前编辑行，那么用户就可以直接编辑了。但是当列表数据为空时，setActiveRow方法会报列表的children不存在，但如果列表原本是有1条或以上数据的，这个逻辑是正常的，我的新增按钮点击的方法如下：
```
var new_row = this.$refs.editable.insert()
this.$refs.editable.setActiveRow(new_row)
```
请问应该在insert后如何操作才能正常使用setActiveRow？或者更好地优化这个新增行的体验？

**Comment by xuliangzhan** [comment]
这样就行了
```javascript
this.$nextTick(() => {
  this.$refs.editable.setActiveRow(row)
})
```

**Comment by xlkit456852** [comment]
完美~原来是$nextTick的问题，谢谢！
