### ISSUE TITLE
使用radio

### ISSUE THREAD

**Issue by hhwsgit** [xuliangzhan/vue-element-extends#144]
**描述 Describe**
我想在点击编辑的时候，出来的是radio标签，应该要怎么做？
:edit-render的name里面没人radio，有其他方法吗？

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**请填写以下版本信息 please complete the following information**
vue: ?
element-ui: ?
vue-element-extends: ?

**Comment by xuliangzhan** [comment]
这个你得使用自定义模板
