### ISSUE TITLE
滚动模式下，复选框disabled能使用吗

### ISSUE THREAD

**Issue by GlenHeart** [xuliangzhan/vue-element-extends#145]
**描述 Describe**

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**请填写以下版本信息 please complete the following information**
vue: ?
element-ui: ?
vue-element-extends: ?

**Comment by xuliangzhan** [comment]
无法支持全选，如果需要该功能可以用这个 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/scroll/scroll
