### ISSUE TITLE
滚动模式下，是否能校验所有的数据。同时定位到有错误的第一行

### ISSUE THREAD

**Issue by GlenHeart** [xuliangzhan/vue-element-extends#146]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by xuliangzhan** [comment]
这个目前不支持

**Comment by GlenHeart** [comment]
这个需求是不是很变态，哈哈

**Comment by xuliangzhan** [comment]
实现是可以，只不过这个是基于 element 有太多的局限性
参考这个，是可以支持的 [vxe-table](https://xuliangzhan.github.io/vxe-table/#/table/scroll/edit)
