### ISSUE TITLE
ElDatePicker选择的日期通过API传到服务器后少了8个小时

### ISSUE THREAD

**Issue by 919946646** [xuliangzhan/vue-element-extends#148]
**问题描述 Describe the bug**
使用elx-editable表
:edit-render="{name: 'ElDatePicker', props: {type: 'date', format: 'yyyy-MM-dd'}}">
使用日期内联修改，当选择的日期通过API传到服务器后少了8个小时
**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**
https://blog.csdn.net/bddj7244112/article/details/86063331
**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - vue: ?
 - element-ui: ?
 - vue-element-extends: ?

**Comment by xuliangzhan** [comment]
你这个是什么数据，那你就把参数加上试试

**Comment by 919946646** [comment]
没到数据库，没保存数据时间就少了8个小时。
:edit-render="{name: 'ElDatePicker', props: {type: 'date', format: 'yyyy-MM-dd'}}"
这行代码里面加不上value-format，只能是 format

**Comment by 919946646** [comment]
可能是问题出在后台JSON格式转化，不是你这儿的问题。你这个扩展控件效果挺好的，给个星支持一下
