### ISSUE TITLE
单元格编辑类型可否加上transfer穿梭框？

### ISSUE THREAD

**Issue by xlkit456852** [xuliangzhan/vue-element-extends#15]
希望能在编辑列中做 选择多个标签（标签列出来让用户选，每选一个添加到单元格中） 的功能，目前element ui组件中只有穿梭框符合要求，但发现本扩展并不支持穿梭框，请问能否把它加进来？或者有其他更好的方法去实现这个功能吗？

**Comment by xuliangzhan** [comment]
单元格能放得下穿梭框？这个需求有点不靠谱
基本所有的组件都可以通过自定义渲染放到单元格，你可以参考[click3](https://xuliangzhan.github.io/vue-element-extends/#/editable/click3)

**Comment by xlkit456852** [comment]
好的谢谢，只能自己去写一个了~

**Comment by xlkit456852** [comment]
文档在编辑吗？好像不见了，想看看el-editable-column支持哪些slot名称~

**Comment by xuliangzhan** [comment]
文档编辑好了哈，现在可以了
