### ISSUE TITLE
使用排序功能之后，如何获取到排过序的数据集合

### ISSUE THREAD

**Issue by wekerSnail** [xuliangzhan/vue-element-extends#153]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**
需要对表格数据操作，但是使用排序功能之后，表格数据的顺序发生了变化，而getRecords拿到的数据还是原数据

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**
希望获取到的数据顺序和表格展示保持一致

**是否有不错的替代方案 Describe alternatives you've considered**
无

**Comment by xuliangzhan** [comment]
这个要 element 支持才行，你可以通过 ref 去读取 el-table内部 tableData 变量就可以获取排序后的数据
