### ISSUE TITLE
后续能支持 ‘插入新列‘ ’和 ‘’手动合并单元格‘ ’吗 

### ISSUE THREAD

**Issue by codeinmyself** [xuliangzhan/vue-element-extends#154]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by xuliangzhan** [comment]
动态插入列个要 element 本身支持才行，如果需要可以用这个支持 [vxe-table](https://xuliangzhan.github.io/vxe-table/#/table/grid/basic)
