### ISSUE TITLE
不支持element-uI的render-header事件，需求背景是想在header上使用下拉框

### ISSUE THREAD

**Issue by codeinmyself** [xuliangzhan/vue-element-extends#156]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by xuliangzhan** [comment]
这个你可以使用 slots header

**Comment by codeinmyself** [comment]
谢谢，还有上一个问题已修改问题描述，context-menu-config 表格右键菜单配置（如果是自定义 code 可以配合 custom-menu-link 事件使用）。
但测试后发现只有bodyMenus可以支持自定义事件，headerMenus不能支持custom-menu-link 事件。

**Comment by xuliangzhan** [comment]
#155
