### ISSUE TITLE
ElSelect组件能否实现多选？

### ISSUE THREAD

**Issue by snowdream** [xuliangzhan/vue-element-extends#157]
**问题描述 Describe the bug**
https://element.eleme.cn/#/zh-CN/component/select
ElSelect组件能否实现多选？

**重现问题的步骤 To Reproduce**
使用element的组件中，有一个需要用到多选。
同时需要用vue-element-extends展示，也希望实现多选。

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**报错信息或截图 Error message or screenshots**
![下载 (4)](https://user-images.githubusercontent.com/737958/60852107-e2dc7100-a228-11e9-9de7-4c87304acb30.png)

**期望的结果 Expected behavior**
ElSelect支持多选

**请填写以下版本信息 please complete the following information**
 - vue: 2.6.9
 - element-ui: 2.4.6
 - vue-element-extends: 1.2.12

**Comment by xuliangzhan** [comment]
这个和表格没关系，组件能支持就能渲染
https://xuliangzhan.github.io/vue-element-extends/#/editable/click9
