### ISSUE TITLE
页面循环出多个editable，如何正确地使用

### ISSUE THREAD

**Issue by owen4comes** [xuliangzhan/vue-element-extends#16]
正在开发一个日历页面，点击日历中的天数，会弹出当天的editable，并编辑。
但目前无法使用this.$refs.editable这种方法去使用相关方法，因为页面内有很多个这样的table，在这种情况下应该如何正确使用？

**Comment by xuliangzhan** [comment]
如果有多个相同的 ref 时 $refs 会得到一个实例数组，你可以数组的索引去操作 this.$refs.editable[index]
或者使用动态 :ref

参考：https://jsfiddle.net/8n17d6gf/
