### ISSUE TITLE
可以支持让所有行都是编辑状态的方法吗？

### ISSUE THREAD

**Issue by tushuyuehou** [xuliangzhan/vue-element-extends#160]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**
可以支持让所有行都是编辑状态的方法吗？

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**
例如我现在有5条数据，点击一下table，让整个table所有的行都是编辑，而不是只有点击的那一行

**是否有不错的替代方案 Describe alternatives you've considered**

**Comment by xuliangzhan** [comment]
所有行都编辑没必要用这个组件，用 el-table 自定义模板就行
