### ISSUE TITLE
拉下之前的项目，npm i并启动后报错,求指点

### ISSUE THREAD

**Issue by chocolate1** [xuliangzhan/vue-element-extends#161]
**描述 Describe**
启动项目后报错Error in render: "TypeError: Cannot create property 'append' on boolean 'true'"

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

![image](https://user-images.githubusercontent.com/26320639/61368998-b6c48e00-a8c1-11e9-82f5-1de62872e88a.png)

**请填写以下版本信息 please complete the following information**
vue: ?2.6.0
element-ui: ?2.4.5
vue-element-extends: ?1.2.21

**Comment by xuliangzhan** [comment]
#66
你应该检查 vue 版本
