### ISSUE TITLE
报错提示是否注册

### ISSUE THREAD

**Issue by flyingrookie** [xuliangzhan/vue-element-extends#162]
**问题描述 Describe the bug**
按照github的demo报错如下:
Unknown custom element: <el-table> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
Unknown custom element: <el-table-column> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**重现问题的步骤 To Reproduce**
![image](https://user-images.githubusercontent.com/30014426/61392627-cf4c9c80-a8f1-11e9-8c12-b241ce690dcd.png)

![image](https://user-images.githubusercontent.com/30014426/61392597-c065ea00-a8f1-11e9-8a5e-dec3b67dcbcb.png)

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**报错信息或截图 Error message or screenshots**
![image](https://user-images.githubusercontent.com/30014426/61392503-8dbbf180-a8f1-11e9-801f-c26504c0673a.png)

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the following information**
 - vue: ?
 - element-ui: ?
 - vue-element-extends: ?

**Comment by xuliangzhan** [comment]
这个你应该检查 element table 是否引入
