### ISSUE TITLE
[Vue warn]: Error in v-on handler (Promise/async): "TypeError: Cannot read property 'querySelector' of undefined"

### ISSUE THREAD

**Issue by dolphinfine** [xuliangzhan/vue-element-extends#164]
**问题描述 Describe the bug**
第一次选择性别时，控制台报错：[Vue warn]: Error in v-on handler (Promise/async): "TypeError: Cannot read property 'querySelector' of undefined"

**重现问题的步骤 To Reproduce**
选择性别

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**
[https://codesandbox.io/s/vue-template-75398](https://codesandbox.io/s/vue-template-75398)

**报错信息或截图 Error message or screenshots**
![image](https://user-images.githubusercontent.com/27426130/61760623-bc106400-adfe-11e9-9c4b-68b894d1ca25.png)

**期望的结果 Expected behavior**
运行正常，不报错。

**请填写以下版本信息 please complete the following information**
 - vue: 2.5.22
 - element-ui: 2.10.1
 - vue-element-extends: 1.2.21

**Comment by xuliangzhan** [comment]
这个是因为你的数据存在未定义字段，导致被重新定义引用发生改变，你应该先定义好或者更新到最新
