### ISSUE TITLE
树型表格如何默认全部展开

### ISSUE THREAD

**Issue by weiguoshengaini** [xuliangzhan/vue-element-extends#165]
expandAll () {
      this.$nextTick(()=>{
          const els = this.$el.getElementsByClassName('el-table__expand-icon')
          for (let i = 0; i < els.length; i++) {
            els[i].click()
          }
      })
    },
  有尝试过使用点击元素，但没有效果

**Comment by xuliangzhan** [comment]
你这个你应该看 element-ui 的文档，可以指定 key 展开

**Comment by weiguoshengaini** [comment]
> 你这个你应该看 element-ui 的文档，可以指定 key 展开

 虽然觉得很奇怪，把最后行的 fixed="right" 的代码去掉，上面的代码就生效了。 ^_^!

**Comment by xuliangzhan** [comment]
感觉和 fixed 的关系应该不大吧 哈，你根据 elementui 的文档应该就可以设置默认展开
