### ISSUE TITLE
开始日期和结束日期怎么做控制呢？谢谢

### ISSUE THREAD

**Issue by wenyongzhao** [xuliangzhan/vue-element-extends#17]
![image](https://user-images.githubusercontent.com/30223381/53721114-5fd39480-3e9d-11e9-8017-a7cec09928bd.png)
开始日期和结束日期怎么做控制呢？谢谢

**Comment by xuliangzhan** [comment]
只要被渲染的日期组件能支持这个功能，把相关的参数放到 attrs 传过去就行，参考[dblclick2](https://xuliangzhan.github.io/vue-element-extends/#/editable/dblclick2)
```html
<el-editable-column prop="date" label="日期" :edit-render="{name: 'ElDatePicker', attrs: {}"></el-editable-column>
```

**Comment by wenyongzhao** [comment]
已经解决了，非常感谢
