### ISSUE TITLE
table中select allowCreate无效

### ISSUE THREAD

**Issue by kevinKaiF** [xuliangzhan/vue-element-extends#175]
**问题描述 Describe the bug**

table设置select的editorRender的props为allowCreate无效，选中是有效果的，但是数据没有渲染到表格中。当鼠标重新点开select列表，可以看到新增的数据是存在的，但是表格中没有展示
**重现问题的步骤 To Reproduce**
`<elx-editable-column prop="sexs" label="性别" width="160" :edit-render="{name: 'ElSelect', options: sexList, props: {filterable: true, clearable: true, allowCreate: true}}"></elx-editable-column>`
**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**
参考：https://xuliangzhan.github.io/vue-element-extends/#/editable/click9 

**报错信息或截图 Error message or screenshots**
![image](https://user-images.githubusercontent.com/17704984/63338391-4a7ff300-c375-11e9-96a2-7fb494beccd6.png)
![image](https://user-images.githubusercontent.com/17704984/63338411-579ce200-c375-11e9-83ef-4364e1e66777.png)
![image](https://user-images.githubusercontent.com/17704984/63338448-66839480-c375-11e9-97b0-3921318ac911.png)
![image](https://user-images.githubusercontent.com/17704984/63338462-6e433900-c375-11e9-85aa-7ecf78f75128.png)

**期望的结果 Expected behavior**
期望可以在表格中select allowCreate生效

**请填写以下版本信息 please complete the following information**
 - vue: 2.6.10
 - element-ui: 2.7.0
 - vue-element-extends: 1.2.22

**Comment by xuliangzhan** [comment]
某些特殊的功能可能无法支持，你可以使用自定义模板解决
