### ISSUE TITLE
https://github.com/livelyPeng/pl-table 流畅渲染万级数据并不会影响到 element-ui el-table组件的原有功能，并且新增了一些功能

### ISSUE THREAD

**Issue by livelyPeng** [xuliangzhan/vue-element-extends#187]
https://github.com/livelyPeng/pl-table 流畅渲染万级数据并不会影响到 element-ui el-table组件的原有功能，并且新增了一些功能

**Comment by xuliangzhan** [comment]
建议你可以把文档完善一些，相信可以实现更好的 el-element 表格组件😄

**Comment by livelyPeng** [comment]
我觉得你们实现得太复杂了，改改源码就好了 哈哈哈

**Comment by xuliangzhan** [comment]
改源码的方式如果 element-ui 版本一旦更新，代码同步问题无法避免

**Comment by livelyPeng** [comment]
不会的啊 哈哈 固定了的哦




------------------ 原始邮件 ------------------
发件人: "Xu Liangzhan"<notifications@github.com>; 
发送时间: 2019年10月12日(星期六) 中午12:34
收件人: "xuliangzhan/vue-element-extends"<vue-element-extends@noreply.github.com>; 
抄送: "Simple love"<403802162@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xuliangzhan/vue-element-extends] https://github.com/livelyPeng/pl-table 流畅渲染万级数据并不会影响到 element-ui el-table组件的原有功能，并且新增了一些功能 (#187)




改源码的方式如果 element-ui 版本一旦更新，代码同步问题无法避免
