### ISSUE TITLE
可拖动表格

### ISSUE THREAD

**Issue by luocong2016** [xuliangzhan/vue-element-extends#21]
用的是sorttable js, 视图是可以拖动，但是怎么保存数据

**Comment by xuliangzhan** [comment]
sortablejs 是直接操作dom，可能会导致数据不同步的问题；如果是行拖动，需要指定 rowKey 并确保在拖动完成后保持与 data 数据同步更新

**Comment by luocong2016** [comment]
row-key 好像传不下去
onEnd: this.rowChangeCb
是这样实现？
rowChangeCb({ newIndex, oldIndex }) { // 行拖拽
      // const currRow = this.datas.splice(oldIndex, 1)[0]
      // this.datas.splice(newIndex, 0, currRow)
      // this._updateData();
 },

**Comment by xuliangzhan** [comment]
你看下 https://jsfiddle.net/cra6k5zd/

**Comment by luocong2016** [comment]
那能有table全编辑状态？

**Comment by xuliangzhan** [comment]
全编辑状态是什么意思？
