### ISSUE TITLE
 行编辑+校验+行操作+树表格 页面无法删除数据

### ISSUE THREAD

**Issue by zhuangyin8** [xuliangzhan/vue-element-extends#24]
https://xuliangzhan.github.io/vue-element-extends/#/editable/manual5
 行编辑+校验+行操作+树表格 页面

bug:
1. 无法成功删除数据
2. 新增数据是点击取消无法放弃更改,还是新增一条空白数据
3. 方法和变量没有注释

新增功能
1. 实现点击目录,在该目录下新增文件

**Comment by xuliangzhan** [comment]
你说的是demo不能删除吗？那个数据是模拟的，没真实删除数据；至于实际的业务逻辑你得自己去实现
