### ISSUE TITLE
请问新增好几条数据到表格中时怎么激活第一行为编辑状态

### ISSUE THREAD

**Issue by shawncai** [xuliangzhan/vue-element-extends#25]
请问新增好几条数据到表格中时怎么激活第一行为编辑状态

**Comment by xuliangzhan** [comment]
setActiveRow(row) 就可以激活指定行

**Comment by shawncai** [comment]
好的谢谢

张存财

在 2019年3月14日，18:14，Xu Liangzhan <notifications@github.com<mailto:notifications@github.com>> 写道：


setActiveRow(row) 就可以激活指定行
