### ISSUE TITLE
使用报Property or method "scope" is not defined on the instance

### ISSUE THREAD

**Issue by kila1314love** [xuliangzhan/vue-element-extends#29]
Property or method "scope" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

**Comment by xuliangzhan** [comment]
最好是能提供下重现问题的[链接](https://jsrun.net/zTXKp/edit)或调用代码

**Comment by xuliangzhan** [comment]
#44
