### ISSUE TITLE
为什么我使用v-slot:edit时会报错啊

### ISSUE THREAD

**Issue by shawncai** [xuliangzhan/vue-element-extends#30]

**Comment by xuliangzhan** [comment]
vue2.6以上语法
```html
<template v-slot:edit="scope"><template>
```
vue2.6以下语法
```html
<template slot="edit" slot-scope="scope"><template>
```

**Comment by shawncai** [comment]
了解，太谢谢了

张存财

在 2019年3月20日，18:23，Xu Liangzhan <notifications@github.com<mailto:notifications@github.com>> 写道：


vue2.6以上语法

<template v-slot:edit="scope"><template>

vue2.6以下语法

<template slot="edit" slot-scope="scope"><template>
