### ISSUE TITLE
关于及时修改，及时响应的问题。

### ISSUE THREAD

**Issue by snowdream** [xuliangzhan/vue-element-extends#32]
getAllRecords | 获取表格数据集合 | —
-- | -- | --
getRecords | 获取表格数据，也可以指定索引获取某条数据 | index
getInsertRecords | 获取新增数据 | —
getRemoveRecords | 获取已删除数据 | —
getUpdateRecords | 获取已修改数据

举个例子：
步骤一：  我添加，修改，删除了一些数据。
步骤二： 我在clear-active事件响应中，应用了这些修改。也就是将数据更改同步到服务器。
步骤三：我再次添加，修改，删除了一些数据。
步骤四：我在clear-active事件响应中，发现：
步骤一所做的添加，修改，删除的数据，仍然在里面。

我的预期：
步骤一修改后，我处理了，同步到服务器。
此时应该把修改后的数据作为原始数据。
步骤三中的修改，应该相当于在原始数据上修改。

不知道有没有表达清楚。

**Comment by snowdream** [comment]
@xuliangzhan 我看到示例中的做法是，任何修改同步到服务器后，重新从服务器请求数据。
是否可以不做最后一步，重新请求数据？

**Comment by xuliangzhan** [comment]
只有调了reload或reloadRow才能把数据状态改变为原始数据；否则都会认为是改动状态

**Comment by snowdream** [comment]
@xuliangzhan 感谢关注。为安全起见，还是按照你的做法做。
