### ISSUE TITLE
可以在select和input里再加个change事件么，以方便完成autocomplete

### ISSUE THREAD

**Issue by CleverF** [xuliangzhan/vue-element-extends#33]
ovo

**Comment by xuliangzhan** [comment]
通过 events 传递或者使用自定义渲染

示例都有[Manual7](https://github.com/xuliangzhan/vue-element-extends/blob/master/examples/views/editable/Manual7.vue)

**Comment by pengxianggui** [comment]
> 通过 events 传递或者使用自定义渲染
> 
> 示例都有[Manual7](https://github.com/xuliangzhan/vue-element-extends/blob/master/examples/views/editable/Manual7.vue)

首先感谢开源精神！
一楼提的我理解的是实现每个单元格编辑完毕后触发保存，这个功能我没有找到，请问这个该如何实现呢。谢谢

**Comment by xuliangzhan** [comment]
最好提供[链接](https://jsrun.net/zTXKp/edit)或调用代码

**Comment by xuliangzhan** [comment]
@pengxianggui  可以在 blur-active 失焦事件处理
