### ISSUE TITLE
请问，如何对某个单独的单元格进行禁用（即无法被编辑），类似于element-ui中的disabled属性？

### ISSUE THREAD

**Issue by demokerle** [xuliangzhan/vue-element-extends#34]
如题，承蒙回答，感谢。

**Comment by xuliangzhan** [comment]
示例都有[click10](https://xuliangzhan.github.io/vue-element-extends/#/editable/click10)

**Comment by demokerle** [comment]
> 示例都有[click10](https://xuliangzhan.github.io/vue-element-extends/#/editable/click10)

收到，非常感谢！
