### ISSUE TITLE
请问，如何获取更改数据的行列信息？

### ISSUE THREAD

**Issue by PizerLiu** [xuliangzhan/vue-element-extends#37]
如题，感谢

**Comment by PizerLiu** [comment]
或者是有数据发生更新的事件操作？

**Comment by xuliangzhan** [comment]
你可以在点击保存时调用getAllRecords方法可以得到增删改的变动数据
示例都有增删改查 [click2](https://xuliangzhan.github.io/vue-element-extends/#/editable/click2)

**Comment by PizerLiu** [comment]
问题就是我这没有按键事件，要直接监控表格数据更改后发送更新接口





| |
lc438732659
邮箱：lc438732659@163.com
|

签名由 网易邮箱大师 定制

在2019年03月25日 20:32，Xu Liangzhan 写道：

你可以在点击保存时调用getAllRecords方法可以得到增删改的变动数据
示例都有增删改查 click2

**Comment by xuliangzhan** [comment]
你可以给编辑的列加个change事件，最好提供下问题[链接](https://jsrun.net/zTXKp/edit)或调用代码
```html
<el-editable-column prop="name" label="Name" :edit-render="{name: 'ElInput', events: {change: changeEvent}}"></el-editable-column>
```

**Comment by PizerLiu** [comment]
麻烦作者events的文档再清楚点，另外，change里的方法怎么传参那？
