### ISSUE TITLE
ElSelect使用普通数组要怎样表示label和value

### ISSUE THREAD

**Issue by wsosw** [xuliangzhan/vue-element-extends#38]
示例中为这种形式
configTypes:[
   {label: '气象站', value: '1'},
   {label: '墒情站', value: '2'}
]
现在这种形式只设置 options：deviceTypes ，选择器不显示内容，要怎样才能让这样的数组显示呢
deviceTypes: ['主机', '传感器', '配件', '其他'],

**Comment by xuliangzhan** [comment]
要么转换格式，要么使用自定义渲染
