### ISSUE TITLE
自定义渲染多级属性，输入符合规则的值也会校验不通过

### ISSUE THREAD

**Issue by co-kevin** [xuliangzhan/vue-element-extends#39]
## 重现

当 prop 为多级时，可以正确提示验证消息，但是输入符合规则的值也会校验不通过

```
<el-editable-column prop="product.name" label="产品名字" min-width="160" show-overflow-tooltip :edit-render="{type: 'default'}">
  <template v-slot="{ row }">
    {{row.product.name}}
  </template>
  <template v-slot:edit="{ row }">
    <el-input v-model="row.product.name"></el-input>
  </template>
</el-editable-column>
```

```
validRules: {
  'product.name': [
    { required: true, message: '请输入名称', trigger: 'change' },
    { min: 3, max: 50, message: '名称长度 4-20 个字符', trigger: 'change' }
  ]
}
```

### 尝试定位问题

editable.vue, line: 885 method `_validCellRules (type, row, column)`

这个方法获取单元格 value 值的时候是采用方括号语法，导致取不到多级属性值

### 尝试解决

可以使用 `eval(`row.data.${property}`)` 方法动态获得多级属性值，可能会有安全风险。更好的作法是 '.' 劈开property,循环取得可能存在的多级属性值

不知这样解决会不会带来其他的问题？

**Comment by co-kevin** [comment]
Fixed https://github.com/hookszhang/vue-element-extends/commit/232be16b928059afa13fc1cb1dc1a47daf8c5c54#diff-6bff884816f886758446498830e6c3d3R17

**Comment by xuliangzhan** [comment]
多谢您的问题定位，多级属性下确实有该问题，在1.0.8+版本解决了，建议更新下
