### ISSUE TITLE
为什么我定义@edit-active时间，不起作用呢，控制台一点反应都没有

### ISSUE THREAD

**Issue by wsosw** [xuliangzhan/vue-element-extends#43]
<el-editable  
     ref="editable"
     border
     :data.sync="deviceInfos" 
     @edit-active="watchDeviceType"
     :edit-config="{mode: 'row', showIcon: false, trigger: 'click'}"		
     style="width: 100%;">

方法：
watchDeviceType(row){
	console.log(row);
}

**Comment by xuliangzhan** [comment]
在1.0.9+版本解决了，建议更新下

**Comment by wsosw** [comment]
好的谢谢
