### ISSUE TITLE
求助，一直报这个错：Duplicate presence of slot "default" found in the same render tree - this will likely cause render errors.

### ISSUE THREAD

**Issue by unssnu** [xuliangzhan/vue-element-extends#44]
### 然后我将项目中的代码直接复制进我的vue文件，也是报这个错，实在找不到原因。。。跪求帮助

vue.runtime.esm.js:587 [Vue warn]: Duplicate presence of slot "default" found in the same render tree - this will likely cause render errors.

`<el-editable
        ref="editable"
        border
        size="mini"
        :data.sync="visitorInfoList"
        :edit-rules="validRules"
        :edit-config="{trigger: 'click', mode: 'row'}"
        style="width: 100%">`
       ` <el-editable-column type="selection" width="55"></el-editable-column>`
        `<el-editable-column prop="visitorName" label="姓名" :edit-render="{name: 'ElInput'}"></el-editable-column>`
        `<el-editable-column prop="gender" label="性别" :edit-render="{name: 'ElSelect', options: sexList}"></el-editable-column>`
       ` <el-editable-column prop="phoneNo" label="手机号码" :edit-render="{name: 'ElInput'}"></el-editable-column>`
       ` <el-editable-column prop="plateNo" label="车牌号码" :edit-render="{name: 'ElInput'}"></el-editable-column>`
        `<el-editable-column prop="certificateNo" label="身份证号" :edit-render="{name: 'ElInput'}"></el-editable-column>`
        `<el-editable-column label="操作" width="100">`
          `<template v-slot="scope">`
            `<el-button size="mini" type="danger" @click="removeEvent(scope.row)">删除</el-button>`
          `</template>`
        `</el-editable-column>`
`</el-editable>`

**Comment by xuliangzhan** [comment]
你应该检查下vue和element版本，和这问题类似 #30

**Comment by unssnu** [comment]
可以了，非常感谢！！！

**Comment by liuchong1995** [comment]
老哥你是怎么解决的??

**Comment by unssnu** [comment]
> 老哥你是怎么解决的??

v-slot="scope"，改成slot-scope="scope"，试试
