### ISSUE TITLE
如何保存  type="index"的索引值到数据库

### ISSUE THREAD

**Issue by snowdream** [xuliangzhan/vue-element-extends#45]
<el-editable-column
        type="index"
        width="55"></el-editable-column>

如题，如何保存  type="index"的索引值到数据库。

**Comment by xuliangzhan** [comment]
不太明白你的问题，data 数组迭代就能拿到索引，传索引的意义在哪里？

**Comment by snowdream** [comment]
@xuliangzhan 已经搞定了。就是拿data 数组长度。
