### ISSUE TITLE
一行只能使用一次ElSelect组件，多次使用options配置项冲突

### ISSUE THREAD

**Issue by JingGeGe77** [xuliangzhan/vue-element-extends#48]

**Comment by xuliangzhan** [comment]
描述不明确，最好提供下能重现的[问题链接](https://jsrun.net/zTXKp/edit)或调用代码

**Comment by JingGeGe77** [comment]
`        <el-editable-column prop="select" label="Select" :edit-render="{name: 'ElSelect', options, attrs: {clearable:true}, type:'visible'}" ></el-editable-column>
        <el-editable-column prop="select1" label="Select1" :edit-render="{name: 'ElSelect', options, attrs: {clearable:true}, type:'visible'}" ></el-editable-column>`

就是data里面只能定义一个options，目前只能使用slot的写法

**Comment by xuliangzhan** [comment]
ElSelect下拉组件还能有多个 options ？
非常规组件渲染请使用自定义模板

**Comment by JingGeGe77** [comment]
问题描述有问题，已解决，感谢
