### ISSUE TITLE
渲染已有数据

### ISSUE THREAD

**Issue by wangjun043179** [xuliangzhan/vue-element-extends#49]
你好，我想问下，我现在已有一些数据，比如我从excell表格中得到数据，是数组嵌套对象的那种格式，我怎么渲染到表格里
![TIM截图20190403120604](https://user-images.githubusercontent.com/44045271/55452186-1778d500-5609-11e9-9ed9-ebc25b0c8858.png)

**Comment by xuliangzhan** [comment]
赋值使用 data 属性，最好提供下能重现的[问题链接](https://jsrun.net/zTXKp/edit)或调用代码

**Comment by wangjun043179** [comment]
那我需要写到哪里，把数据进行循环渲染到表格里。
![TIM截图20190403140916](https://user-images.githubusercontent.com/44045271/55456739-5cf1ce00-561a-11e9-89fb-c7e8f6324afc.png)
![TIM截图20190403140930](https://user-images.githubusercontent.com/44045271/55456744-61b68200-561a-11e9-9be8-e66713a14c65.png)
![TIM截图20190403141035](https://user-images.githubusercontent.com/44045271/55456753-64b17280-561a-11e9-842e-c659f7aba5c1.png)
最后我需要渲染成这种情况
![TIM截图20190403141228](https://user-images.githubusercontent.com/44045271/55456795-87dc2200-561a-11e9-8232-95fbb3a19d76.png)
就是把我已有的数组渲染到表格里

**Comment by xuliangzhan** [comment]
你表格中的数据都在list里面，你把list放到data里面，就不需要使用reload了；然后就可以直接操作list数据了
```html
<el-editable
      ref="editable"
      class="excel-table4"
      border
      size="customSize"
      :data.sync="list"
      :edit-rules="validRules"
      :edit-config="{trigger: 'dblclick', showIcon: false, showStatus: false, isTabKey: true, isArrowKey: true}"
      style="width: 100%" >
</el-editable>
```

**Comment by wangjun043179** [comment]
就是我现在的数据是已经有的，但是我要渲染到原本空的excell表格里，怎么搞
![TIM截图20190403152718](https://user-images.githubusercontent.com/44045271/55461290-b2cc7300-5626-11e9-9f61-ba161ba3c516.png)
![TIM截图20190403153856](https://user-images.githubusercontent.com/44045271/55461302-b65ffa00-5626-11e9-99e3-534cf423db93.png)

**Comment by wangjun043179** [comment]
我看了直接把list赋值为那个数组，不行，渲染不出来

**Comment by xuliangzhan** [comment]
你是怎么赋值的，对data的操作都是双向的，都会实时同步到表格中

**Comment by wangjun043179** [comment]
那我如果现有数据和表格长度对不上，可以循环么？就是表格不是26列，然后我现在数据只有4/5列，直接赋值也可以吗？

**Comment by wangjun043179** [comment]
我就是直接把现有数据赋值给list

**Comment by xuliangzhan** [comment]
这个怎么处理数据你要自己去实现，表格最终只会根据data的值去渲染，你只需要确保data数据字段个值是正确的就行
