### ISSUE TITLE
Tab键切换，进入编辑后会清空之前的值

### ISSUE THREAD

**Issue by zhangyugeng** [xuliangzhan/vue-element-extends#51]
Tab键切换，进入编辑后会清空之前的值。如何才能不清空.
![image](https://user-images.githubusercontent.com/41097997/55474176-1c5a7a80-5643-11e9-804d-1a4bfda3f8b4.png)
![image](https://user-images.githubusercontent.com/41097997/55474240-3a27df80-5643-11e9-98a1-d2ca4528a33d.png)

**Comment by xuliangzhan** [comment]
切换编辑是属于覆盖式的动作，你可以使用参数关闭直接编辑 isCheckedEdit: false

**Comment by zhangyugeng** [comment]
配置了isCheckedEdit:false，通tab切换，按空格进不去编辑。
![image](https://user-images.githubusercontent.com/41097997/55522302-f078dc80-56b6-11e9-82e3-8923ff3b341b.png)
![image](https://user-images.githubusercontent.com/41097997/55522310-f969ae00-56b6-11e9-8a7c-f95cbc45b711.png)

**Comment by xuliangzhan** [comment]
isCheckedEdit:false就是关闭编辑

**Comment by zhangyugeng** [comment]
如何才能在编辑状态下不清空

**Comment by xuliangzhan** [comment]
在1.0.12+版本中可以支持重写 checkedEditMethod 方法，可以实现不清空，可以参考[demo](https://xuliangzhan.github.io/vue-element-extends/#/editable/excel3)
