### ISSUE TITLE
编辑无法输入值

### ISSUE THREAD

**Issue by wangjun043179** [xuliangzhan/vue-element-extends#52]
你好，我这边点击编辑，然后把当前数据传进去，然后excell表格渲染出来，但是只能改原有数据，就是我之前有3列，就只能改那三列，其他的列无法编辑
![TIM截图20190404160616](https://user-images.githubusercontent.com/44045271/55539854-3f913280-56f4-11e9-944f-9c56bdee2166.png)

**Comment by wangjun043179** [comment]
![TIM截图20190404160616](https://user-images.githubusercontent.com/44045271/55539918-694a5980-56f4-11e9-8b75-e65568ff071e.png)

**Comment by xuliangzhan** [comment]
这种问题肯定就是其他字段未定义造成双向绑定失效了，你应该给其他字段设置默认值
或者更新到1.0.11可以支持自动补全字段

**Comment by wangjun043179** [comment]
这个怎么更新

**Comment by xuliangzhan** [comment]
npm install xe-utils vue-element-extends

**Comment by wangjun043179** [comment]
好的  我试试

**Comment by wangjun043179** [comment]
好了，谢谢大佬，感谢感谢。
