### ISSUE TITLE
关于ElDatePicker的使用疑问

### ISSUE THREAD

**Issue by snowdream** [xuliangzhan/vue-element-extends#53]
测试日期： 2019年1月9日

1. el-date-picker  饿了么官方组件
组件使用：
```
      <el-date-picker
              v-model="hetong.shanghuriqi"
              class="hetong-input"
              prefix-icon=""
              type="date"
              placeholder="选择日期"
              format="yyyy 年 MM 月 dd 日"/>
```

通过组件选择日期，存储到mongodb，数据如下：
ISODate("2019-01-08T16:00:00.000Z"),

回显到el-date-picker  ，显示： 2019年1月9日

2. ElDatePicker vue-element-extends组件
组件使用：
```
      <el-editable-column
        :edit-render="{name: 'ElDatePicker', attrs: {type: 'date', format: 'yyyy年MM月dd日'}}"
        label="借款日期"
        prop="jiekuanriqi"
        align="center"
        width="150px"
      />
```
通过组件选择日期，存储到mongodb，数据如下：
ISODate("2019-01-08T16:00:00.000Z"),
回显到表格界面 ，显示： 2019年1月8日

**Comment by xuliangzhan** [comment]
应该是value值有问题，请根据饿了么官方组件文档格式进行赋值

**Comment by snowdream** [comment]
@xuliangzhan 目前现象比较明显，我选择 2019年1月9日，保存之后，会从数据库重新加载数据，然后展示为2019年1月8日。
是我用法不对，还是触发了什么bug？ 帮忙排查一下，谢谢。

**Comment by xuliangzhan** [comment]
和数据库没关系，你应该把操作前后值做对比

**Comment by snowdream** [comment]
MongDB采用的是UTC时间（协调时间时）
@xuliangzhan 和这个有关系吗？

**Comment by snowdream** [comment]
这是我跟踪的js中的一个时间。
我选择的是3月27日，存储的是2019-03-26T16:00:00.000Z。
存储后，从数据库读取回来，回显到表格，数据显示3月26日。

_d: Wed Mar 27 2019 00:00:00 GMT+0800 (中国标准时间) {}
_f: "YYYY-MM-DDTHH:mm:ss.SSSSZ"
_i: "2019-03-26T16:00:00.000Z"
_isAMomentObject: true
_isUTC: false
_isValid: true
_locale: P {_calendar: {…}, _longDateFormat: {…}, _invalidDate: "Invalid date", ordinal: ƒ, _dayOfMonthOrdinalParse: /\d{1,2}(th|st|nd|rd)/, …}
_pf: {empty: false, unusedTokens: Array(0), unusedInput: Array(0), overflow: -1, charsLeftOver: 0, …}
_tzm: 0
__proto__: Object

**Comment by snowdream** [comment]
搞定。

原因：  
组件ElDatePicker选择 3月27日，这里没问题。
mongodb存储时自动转换成utc时间，2019-03-26T16:00:00.000Z
从mongodb加载时间，并通过ElDatePicker展示，这里没把utc时间转换成本地时间（北京时间）,所以展示了3月26日。
ps： 这里对比了element的datepicker标准组件，它可能自动完成了这步骤（utc时间转换成本地时间）。

解决方法：
从mongodb中获取的utc时间，经过momentjs格式化一下，再展示到组件ElDatePicker。

```
      <el-editable-column
        :edit-render="{name: 'ElDatePicker', attrs: {type: 'date', format: 'yyyy年MM月dd日'}}"
        :formatter="formatterDate"
        label="借款日期"
        prop="jiekuanriqi"
        align="center"
        width="150px"
      />


    formatterDate(row, column, cellValue, index) {
      return dateFormatter(cellValue)
    },




import Moment from 'moment-mini'// 导入文件

/**
 * UTC时间转换成本地时间
 *
 * @param utc  utc时间
 * @param formatString 时间格式
 * @returns {number}  本地时间
 */
export function dateFormatter(utc, formatString) {
  formatString = formatString || 'YYYY年MM月DD日'
  return Moment(utc).format(formatString)
}
```

**Comment by snowdream** [comment]
@xuliangzhan 希望ElDatePicker组件在展示时间时，自动将utc时间转换回本地时间再展示。

**Comment by xuliangzhan** [comment]
Editable 只会根据数据渲染，不处理具体数据是什么格式；
至于 ElDatePicker 组件相关的使用你应该查看 elementui 文档或提相关问题

**Comment by snowdream** [comment]
只是提醒一下。elementui组件ElDatePicker会自动将utc转换成本地时间。Editable的ElDatePicker不会自动转换。

**Comment by xuliangzhan** [comment]
@snowdream 你可以更新到最新试下，可以支持转换

**Comment by ibmsoft** [comment]
这个确实是有问题的
我这边用的日期组件，后台保存的是字符串 
  :edit-render="{name: 'ElDatePicker',props: {type: 'month','value-format':'yyyyMM'}}"
后台返回 201908，前端会显示201907

**Comment by xuliangzhan** [comment]
@ibmsoft 有问题请用重现链接来描述你的问题
