### ISSUE TITLE
ElSelect 禁止编辑

### ISSUE THREAD

**Issue by snowdream** [xuliangzhan/vue-element-extends#54]
<elx-editable-column
        prop="sex"
        label="下拉"
        :edit-render="{name: 'ElSelect', options: sexList}"></elx-editable-column>

sexList：
[
  {
    "label": "男",
    "spell": "nan",
    "value": "1",
    "val": "x"
  },
  {
    "label": "女",
    "spell": "nv",
    "value": "0",
    "val": "o"
  }
]

如果我已经存储了sex值，然后再其他地方回显的时候，不想使用ElSelect下拉组件，只想展示sex值，应该怎么做？

**Comment by xuliangzhan** [comment]
使用 activeMethod 该方法就可以实现，可以控制到某个单元格

**Comment by snowdream** [comment]
@xuliangzhan 有几个疑问：
1. activeMethod的返回值true和false代表什么意思，这个没查到。
2. 我需要控制这一列不可编辑，其他列按照设置可编辑或者不可编辑。
3. 在example中没有找到对应的例子。

**Comment by xuliangzhan** [comment]
这里有的 [click10](https://xuliangzhan.github.io/vue-element-extends/#/editable/click10)

**Comment by snowdream** [comment]
参考 click10搞定

**Comment by XdyGoGo** [comment]
click10的demo需要点击才可以继续编辑，没能自动对焦
