### ISSUE TITLE
添加序号列fixed属性，自定义渲染组件会加载两次

### ISSUE THREAD

**Issue by leemeow** [xuliangzhan/vue-element-extends#56]
自定义组件的mounted会执行两次
<el-editable :data="tableData">
	<el-editable-column type="index" align="center" width="50" fixed>
            <template v-slot:header="scope">
                序号
            </template>
    </el-editable-column>
	<el-editable-column prop="name" label="自定义" :edit-render="{}">
            <template v-slot:edit="scope">
                <test-cop v-model="scope.row.name"/>
            </template>
	</el-editable-column>
</el-editable>

**Comment by xuliangzhan** [comment]
这个是 el table 的实现方式，fixed 列实际上也是一份独立渲染的表格
