### ISSUE TITLE
列类型是ElInputNumber且必须填写，输入0怎么验证失败

### ISSUE THREAD

**Issue by xyt861202** [xuliangzhan/vue-element-extends#57]
:edit-render="{name: 'ElInputNumber', attrs: {min: 0, controls: false}}
列类型是ElInputNumber且验证规则required: true时，输入0怎么验证失败，和空值的验证提示一样

**Comment by xuliangzhan** [comment]
在1.0.14+版本中修复了，建议更新下

**Comment by lmy1991** [comment]
`<el-editable-column prop="demandStatus" label="状态" width="160" :edit-render="{name: 'ElSelect', options: statuses}" />
`
demandStatus的值等于0的时候直接就空了

@xuliangzhan

**Comment by xuliangzhan** [comment]
@lmy1991 你可以更新到1.0.16+看下
