### ISSUE TITLE
怎么设置时间控件的可选择的起始时间

### ISSUE THREAD

**Issue by chocolate1** [xuliangzhan/vue-element-extends#59]
<el-editable-column prop="start_time" label="开始时间" align="center"  :edit-render="{name: 'ElDatePicker', attrs: {type: 'datetime', format: 'yyyy-MM-dd HH:mm:ss' }}"></el-editable-column>

一点击变成1970年，而且选择完保存后变成了Invalid Date，请问怎么设置最开始的选择时间点

**Comment by xuliangzhan** [comment]
参数你应该查看 elementui 的文档，最好提供下能重现的[问题链接](https://jsrun.net/HFXKp/edit)或调用代码

**Comment by chocolate1** [comment]
![image](https://user-images.githubusercontent.com/26320639/56401289-b4cf3c80-628a-11e9-94e0-69d77c2dae53.png)

编辑保存后，当时间为1970年及之前的时间都会变成
![image](https://user-images.githubusercontent.com/26320639/56401266-a08b3f80-628a-11e9-99fc-afc33485b543.png)
找不出是哪里的问题，所以向您请教一下
![image](https://user-images.githubusercontent.com/26320639/56401351-f364f700-628a-11e9-8b01-2954076e938e.png)

**Comment by chocolate1** [comment]
而且，为什么面板上的时间是1970，我设置的默认时间（当前时间）
![image](https://user-images.githubusercontent.com/26320639/56401427-4ccd2600-628b-11e9-8236-45e67355bf6e.png)

**Comment by xuliangzhan** [comment]
你应该看下参数，出入参

**Comment by chocolate1** [comment]
上礼拜解决了，是1970这个特殊的时间问题，谢谢
