### ISSUE TITLE
关于在行编辑下datePicker统一修改的问题？

### ISSUE THREAD

**Issue by jacksparrow414** [xuliangzhan/vue-element-extends#64]
在el-editable中的column加入datePicker选择器，每一行添加编辑按钮，点击编辑按钮，这一行的datePicker变为可用。
目前出现的情况为：在某一行点击编辑按钮，会全局修改datePicker对应的值，使得其他没有开启行编辑的行对应的列也变为了可编辑的了。
请教如何解决呢？
<img width="662" alt="屏幕快照 2019-04-15 下午3 20 48" src="https://user-images.githubusercontent.com/33389378/56114069-50626380-5f92-11e9-9979-35d66fdd5f1f.png">
通过disabled的值，动态修改为true或者false,但是这样就会修改所有行，如何只修改当前行的datePicker可用

**Comment by xuliangzhan** [comment]
不太明白你的问题，最好提供下能重现的[问题链接](https://jsrun.net/zTXKp/edit)
