### ISSUE TITLE
使用时 报key of null

### ISSUE THREAD

**Issue by a1609960351** [xuliangzhan/vue-element-extends#66]
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:602 [Vue warn]: Error in render: "TypeError: Cannot read property 'key' of null"

found in

---> <ElxEditable>
       <PaymentDetail> at src/components/page/paymentDetail.vue
         <Home> at src/components/common/Home.vue
           <App> at src/App.vue
             <Root>
 在同事的同环境下 代码一模一样  我的报这个错误   怎么办。。。

**Comment by xuliangzhan** [comment]
这个没看出是组件报错了

**Comment by gaozhidong** [comment]
![image](https://user-images.githubusercontent.com/21300913/56335028-66a83380-61cd-11e9-992f-c2d638037e6d.png)

![image](https://user-images.githubusercontent.com/21300913/56335067-8a6b7980-61cd-11e9-997c-7f36930f894f.png)
![image](https://user-images.githubusercontent.com/21300913/56335073-93f4e180-61cd-11e9-968f-a2634b432ad8.png)

**Comment by gaozhidong** [comment]
![image](https://user-images.githubusercontent.com/21300913/56335093-b7b82780-61cd-11e9-8e68-f58fb886924d.png)

**Comment by a1609960351** [comment]
我的和楼上一样。，。。也是这种i情况

**Comment by a1609960351** [comment]
![1555559942(1)](https://user-images.githubusercontent.com/41106198/56336032-627e1500-61d1-11e9-9892-1e5f005fff50.jpg)
![1555560004(1)](https://user-images.githubusercontent.com/41106198/56336075-85102e00-61d1-11e9-9261-b3a7afa2af10.jpg)

**Comment by gaozhidong** [comment]
[https://github.com/gaozhidong/keyNull](https://github.com/gaozhidong/keyNull)只是引用**ElementUI**和使用**ue-element-extends**是没有报错的，应该是某个包引起吧！

**Comment by xuliangzhan** [comment]
@gaozhidong 看你截图那个报错和slot有关，提供下所有依赖包版本信息看下

**Comment by gaozhidong** [comment]
[依赖列表](https://gaozhidong.github.io/keyNull/static/demo.json)

**Comment by xuliangzhan** [comment]
vue 2.6以下不支持vue-element-extends1.1.x+版本，1.1.x+版本需要vue2.6+
vue 2.6以下可以使用1.0.*版本

**Comment by a1609960351** [comment]
@xuliangzhan 
![1555564246(1)](https://user-images.githubusercontent.com/41106198/56338144-73cc1f00-61db-11e9-844d-48e21cdc52c5.jpg)
我这个有问题么

**Comment by xuliangzhan** [comment]
@a1609960351 你这个是用cli3的，vue默认最新，关系不大
如果有问题改成 vue2.6.10 试下

**Comment by a1609960351** [comment]
![1555564796(1)](https://user-images.githubusercontent.com/41106198/56338456-b17d7780-61dc-11e9-934b-7f18bc6493b3.jpg)

**Comment by gaozhidong** [comment]
> vue 2.6以下不支持vue-element-extends1.1.x+版本，1.1.x+版本需要vue2.6+

明白,把vue 升级到^2.6.10解决报错问题，谢谢

**Comment by Rekoe** [comment]
但我的vue --version  版本已经是3.6.3 还是有这个问题 ，请问 还需要如何排查问题么

**Comment by Rekoe** [comment]
@xuliangzhan

**Comment by xuliangzhan** [comment]
@Rekoe 你把依赖信息列出来

**Comment by Rekoe** [comment]
```
{
  "name": "nutz-onekey",
  "version": "4.0.0",
  "description": "NUTZ-ONEKEY",
  "author": "Kerbores <kerbore@gmail.com>",
  "license": "Apache",
  "scripts": {
    "dev": "node build/dev-server.js",
    "start": "node build/dev-server.js",
    "build": "node build/build.js"
  },
  "dependencies": {
    "autoprefixer": "^9.5.1",
    "axios": "^0.17.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-runtime": "^6.0.0",
    "better-scroll": "^0.1.7",
    "bga-back-top-vue": "^1.0.2",
    "element-ui": "^2.0.8",
    "fastclick": "^1.0.6",
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1",
    "js-cookie": "2.2.0",
    "less": "^3.9.0",
    "mint-ui": "^2.2.7",
    "moment": "^2.19.3",
    "normalize.css": "^7.0.0",
    "nprogress": "^0.2.0",
    "store": "^2.0.12",
    "stylus-loader": "^3.0.2",
    "vue": "^2.5.9",
    "vue-element-extends": "^1.2.1",
    "vue-i18n": "^7.3.2",
    "vue-infinite-scroll": "^2.0.2",
    "vue-json-viewer": "^2.1.4",
    "vue-resource": "^1.0.1",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1",
    "vuex-persistedstate": "^2.4.2",
    "vux": "^2.9.4",
    "vux-loader": "^1.2.9",
    "xe-ajax": "^3.5.3",
    "xe-utils": "^1.8.19"
  },
  "devDependencies": {
    "axios-mock-adapter": "^1.7.1",
    "babel-core": "^6.22.1",
    "babel-loader": "^6.2.10",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-polyfill": "^6.16.0",
    "babel-preset-env": "^1.2.1",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^1.1.3",
    "compression-webpack-plugin": "^1.1.3",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.4",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.16.4",
    "extract-text-webpack-plugin": "^2.0.0",
    "file-loader": "^0.10.0",
    "friendly-errors-webpack-plugin": "^1.1.3",
    "function-bind": "^1.0.2",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.17.3",
    "json-loader": "^0.5.4",
    "less-loader": "^4.0.5",
    "mockjs": "^1.0.1-beta3",
    "node-sass": "^4.10.0",
    "opn": "^4.0.2",
    "optimize-css-assets-webpack-plugin": "^1.3.0",
    "ora": "^1.0.0",
    "rimraf": "^2.6.0",
    "sass-loader": "^6.0.0",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "style-loader": "^0.21.0",
    "svg-sprite-loader": "3.5.2",
    "url-loader": "^0.5.8",
    "vue-loader": "^11.1.4",
    "vue-style-loader": "^2.0.0",
    "vue-template-compiler": "^2.2.4",
    "webpack": "^2.2.1",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-hot-middleware": "^2.16.1",
    "webpack-merge": "^2.6.1"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

```

@xuliangzhan

**Comment by xuliangzhan** [comment]
vue-element-extends 1.0.x 对应 vue^2.5+ 、element-ui^2.0~2.6 
vue-element-extends 1.2.x 对应 vue^2.6+ 、element-ui^2.0+
@Rekoe  你的vue版本不支持，你可以升到2.6.10，element-ui版本也太低，可能存在兼容性问题

**Comment by a1609960351** [comment]
{
  "name": "BaiCaiERPClient",
  "version": "0.0.6",
  "private": true,
  "scripts": {
    "dev": "npm run serve",
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "babel-polyfill": "^6.26.0",
    "css-loader": "^2.1.1",
    "element-ui": "^2.4.11",
    "html2canvas": "^1.0.0-alpha.12",
    "mavon-editor": "^2.6.17",
    "mockjs": "^1.0.1-beta3",
    "qrcode": "^1.3.3",
    "qrcodejs2": "0.0.2",
    "qs": "^6.6.0",
    "vue": "^2.5.21",
    "vue-cropperjs": "^3.0.0",
    "vue-element-extends": "^1.2.0",
    "vue-quill-editor": "^3.0.6",
    "vue-router": "^3.0.1",
    "vue-schart": "^1.0.0",
    "vuedraggable": "^2.17.0",
    "vuex": "^3.1.0",
    "xe-utils": "^1.8.19"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.2.0",
    "@vue/cli-service": "^3.2.0",
    "clipboard": "^2.0.4",
    "jsbarcode": "^3.11.0",
    "node-sass": "^4.11.0",
    "sass-loader": "^7.1.0",
    "viewerjs": "^1.3.2",
    "vue-template-compiler": "^2.5.21"
  },
  "devDependencies-description": {
    "qrcodejs2": "二维码生成器",
    "jsbarcode": "条形码生成器"
  }
}
@xuliangzhan  看下我的 我的还是有问题啊。

**Comment by xuliangzhan** [comment]
@a1609960351  你的vue版本都没对上
vue-element-extends 1.0.x 对应 vue^2.5+ 、element-ui^2.0~2.6
vue-element-extends 1.2.x 对应 vue^2.6+ 、element-ui^2.0+

**Comment by Rekoe** [comment]
@xuliangzhan 我的版本是太低了么，请问你是哪里看出版本低的呢？

**Comment by Rekoe** [comment]
@xuliangzhan 升级到这个版本了还是有那个问题
请问还有哪里配置有问题么
```
{
  "name": "nutz-onekey",
  "version": "4.0.0",
  "description": "NUTZ-ONEKEY",
  "author": "Kerbores <kerbore@gmail.com>",
  "license": "Apache",
  "scripts": {
    "dev": "node build/dev-server.js",
    "start": "node build/dev-server.js",
    "build": "node build/build.js"
  },
  "dependencies": {
    "autoprefixer": "^9.5.1",
    "axios": "^0.17.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-runtime": "^6.0.0",
    "better-scroll": "^0.1.7",
    "bga-back-top-vue": "^1.0.2",
    "element-ui": "^2.4.11",
    "fastclick": "^1.0.6",
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1",
    "js-cookie": "2.2.0",
    "less": "^3.9.0",
    "mint-ui": "^2.2.7",
    "moment": "^2.19.3",
    "normalize.css": "^7.0.0",
    "nprogress": "^0.2.0",
    "store": "^2.0.12",
    "stylus-loader": "^3.0.2",
    "vue-element-extends": "^1.2.2",
    "vue-i18n": "^7.3.2",
    "vue-infinite-scroll": "^2.0.2",
    "vue-json-viewer": "^2.1.4",
    "vue-resource": "^1.0.1",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1",
    "vue": "^2.6.10",
    "vuex-persistedstate": "^2.4.2",
    "vux": "^2.9.4",
    "vux-loader": "^1.2.9",
    "xe-ajax": "^3.5.3",
    "xe-utils": "^1.8.19"
  },
  "devDependencies": {
    "axios-mock-adapter": "^1.7.1",
    "babel-core": "^6.22.1",
    "babel-loader": "^6.2.10",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-polyfill": "^6.16.0",
    "babel-preset-env": "^1.2.1",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^1.1.3",
    "compression-webpack-plugin": "^1.1.3",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.4",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.16.4",
    "extract-text-webpack-plugin": "^2.0.0",
    "file-loader": "^0.10.0",
    "friendly-errors-webpack-plugin": "^1.1.3",
    "function-bind": "^1.0.2",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.17.3",
    "json-loader": "^0.5.4",
    "less-loader": "^4.0.5",
    "mockjs": "^1.0.1-beta3",
    "node-sass": "^4.10.0",
    "opn": "^4.0.2",
    "optimize-css-assets-webpack-plugin": "^1.3.0",
    "ora": "^1.0.0",
    "rimraf": "^2.6.0",
    "sass-loader": "^6.0.0",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "style-loader": "^0.21.0",
    "svg-sprite-loader": "3.5.2",
    "url-loader": "^0.5.8",
    "vue-loader": "^11.1.4",
    "vue-style-loader": "^2.0.0",
    "vue-template-compiler": "^2.2.4",
    "webpack": "^2.2.1",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-hot-middleware": "^2.16.1",
    "webpack-merge": "^2.6.1"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

```

**Comment by xuliangzhan** [comment]
> @xuliangzhan 升级到这个版本了还是有那个问题
> 请问还有哪里配置有问题么
> 
> ```
> {
>   "name": "nutz-onekey",
>   "version": "4.0.0",
>   "description": "NUTZ-ONEKEY",
>   "author": "Kerbores <kerbore@gmail.com>",
>   "license": "Apache",
>   "scripts": {
>     "dev": "node build/dev-server.js",
>     "start": "node build/dev-server.js",
>     "build": "node build/build.js"
>   },
>   "dependencies": {
>     "autoprefixer": "^9.5.1",
>     "axios": "^0.17.1",
>     "babel-preset-es2015": "^6.24.1",
>     "babel-runtime": "^6.0.0",
>     "better-scroll": "^0.1.7",
>     "bga-back-top-vue": "^1.0.2",
>     "element-ui": "^2.4.11",
>     "fastclick": "^1.0.6",
>     "font-awesome": "^4.7.0",
>     "jquery": "^3.3.1",
>     "js-cookie": "2.2.0",
>     "less": "^3.9.0",
>     "mint-ui": "^2.2.7",
>     "moment": "^2.19.3",
>     "normalize.css": "^7.0.0",
>     "nprogress": "^0.2.0",
>     "store": "^2.0.12",
>     "stylus-loader": "^3.0.2",
>     "vue-element-extends": "^1.2.2",
>     "vue-i18n": "^7.3.2",
>     "vue-infinite-scroll": "^2.0.2",
>     "vue-json-viewer": "^2.1.4",
>     "vue-resource": "^1.0.1",
>     "vue-router": "^3.0.1",
>     "vuex": "^3.0.1",
>     "vue": "^2.6.10",
>     "vuex-persistedstate": "^2.4.2",
>     "vux": "^2.9.4",
>     "vux-loader": "^1.2.9",
>     "xe-ajax": "^3.5.3",
>     "xe-utils": "^1.8.19"
>   },
>   "devDependencies": {
>     "axios-mock-adapter": "^1.7.1",
>     "babel-core": "^6.22.1",
>     "babel-loader": "^6.2.10",
>     "babel-plugin-transform-runtime": "^6.22.0",
>     "babel-polyfill": "^6.16.0",
>     "babel-preset-env": "^1.2.1",
>     "babel-preset-stage-2": "^6.22.0",
>     "babel-register": "^6.22.0",
>     "chalk": "^1.1.3",
>     "compression-webpack-plugin": "^1.1.3",
>     "connect-history-api-fallback": "^1.3.0",
>     "copy-webpack-plugin": "^4.0.1",
>     "css-loader": "^0.26.4",
>     "eventsource-polyfill": "^0.9.6",
>     "express": "^4.16.4",
>     "extract-text-webpack-plugin": "^2.0.0",
>     "file-loader": "^0.10.0",
>     "friendly-errors-webpack-plugin": "^1.1.3",
>     "function-bind": "^1.0.2",
>     "html-webpack-plugin": "^2.28.0",
>     "http-proxy-middleware": "^0.17.3",
>     "json-loader": "^0.5.4",
>     "less-loader": "^4.0.5",
>     "mockjs": "^1.0.1-beta3",
>     "node-sass": "^4.10.0",
>     "opn": "^4.0.2",
>     "optimize-css-assets-webpack-plugin": "^1.3.0",
>     "ora": "^1.0.0",
>     "rimraf": "^2.6.0",
>     "sass-loader": "^6.0.0",
>     "semver": "^5.3.0",
>     "shelljs": "^0.7.6",
>     "style-loader": "^0.21.0",
>     "svg-sprite-loader": "3.5.2",
>     "url-loader": "^0.5.8",
>     "vue-loader": "^11.1.4",
>     "vue-style-loader": "^2.0.0",
>     "vue-template-compiler": "^2.2.4",
>     "webpack": "^2.2.1",
>     "webpack-dev-middleware": "^1.10.0",
>     "webpack-hot-middleware": "^2.16.1",
>     "webpack-merge": "^2.6.1"
>   },
>   "engines": {
>     "node": ">= 4.0.0",
>     "npm": ">= 3.0.0"
>   },
>   "browserslist": [
>     "> 1%",
>     "last 2 versions",
>     "not ie <= 8"
>   ]
> }
> ```

更新到最新也不行？
npm install vue-element-extends vue

**Comment by Rekoe** [comment]
@xuliangzhan 是的 问题照样存在.

**Comment by Rekoe** [comment]
@xuliangzhan 感觉还是版本的问题 刚开始装的时候不知道是哪个版本的 后来把node-modules文件夹删除 重新npm install的时候就出这个问题了.现在尝试挨个版本的装上试试,不知道你有没有更好的解决这个问题的方法.

**Comment by xuliangzhan** [comment]
试下
npm install vue-element-extends vue@2.6.10
npm install vue-template-compiler@2.6.10 -D

**Comment by Rekoe** [comment]
@xuliangzhan 问题依旧

**Comment by xuliangzhan** [comment]
你可以也像这样搞个空项目调试下 https://github.com/gaozhidong/keyNull

**Comment by Rekoe** [comment]
@xuliangzhan  谢谢一直的指导 问题解决了,问题还是出在vue版本,我检查了一下 我的项目vue的引入通过index.html引入的版本还是2.5.2,package.json的vue版本设置未生效,所以还是提醒遇到这个问题的同学 优先检查vue版本.

**Comment by zhaoyuqing7** [comment]
同样得问题，报key of null

**Comment by Rekoe** [comment]
@zhaoyuqing7 你检查下你的vue版本

**Comment by a1609960351** [comment]
问题已解决。。改下版本号重下依赖就可以了

**Comment by mklm305** [comment]
> 问题已解决。。改下版本号重下依赖就可以了
请问具体是怎么解决的 ，我也遇到了

**Comment by Jia4tin** [comment]
我应该早点看到这个 issue .....
