### ISSUE TITLE
关于修改时的问题

### ISSUE THREAD

**Issue by NIeeeeee** [xuliangzhan/vue-element-extends#68]
你好，如果我希望在失去焦点之前做一次与后台的接口对接，成功之后在失去焦点。然后修改成功。我该如何写啊?

**Comment by xuliangzhan** [comment]
参考这个就行了 [click5](https://xuliangzhan.github.io/vue-element-extends/#/editable/click5)

**Comment by NIeeeeee** [comment]
好的，谢谢~
