### ISSUE TITLE
支持按回车跳到下一个input或者select吗？

### ISSUE THREAD

**Issue by tushuyuehou** [xuliangzhan/vue-element-extends#70]
支持按回车跳到下一个input或者select，然后获取焦点吗？

**Comment by xuliangzhan** [comment]
不支持回车或自行实现;
可以设置 isTab=true, tabToActive=true 通过 Tab 键切换后直接为编辑状态；

**Comment by afx919** [comment]
> 不支持回车或自行实现;
> 可以设置 isTab=true, tabToActive=true 通过 Tab 键切换后直接为编辑状态；

我在elx-editable-column标签里面设置isTab=“true” tabToActive=“true” 并没有作用

**Comment by xuliangzhan** [comment]
建议参考这个 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/edit/keyboard
