### ISSUE TITLE
当tableData长度由100000变为10，elx-scroll_bottom-pace的height属性不会重新计算

### ISSUE THREAD

**Issue by ynzion** [xuliangzhan/vue-element-extends#71]
**问题描述 Describe the bug**
当tableData长度由100000变为10，分两种情况：
如果当时滚动条不处于最下方，则elx-scroll_bottom-pace的height属性不会重新计算。
如果滚动条处于最下方，则会重新计算。

**重现问题的步骤 To Reproduce**
进入下方链接：
直接点击《修改tableData》按钮即可重现问题
先把滚动条拖动至最下方，再点击《修改tableData》按钮，则符合预期

**重现问题的链接（jsfiddle、jsrun） Expected behavior**
https://jsfiddle.net/sw89tbap/

**报错信息或截图 Error message or screenshots**
![image](https://user-images.githubusercontent.com/39619397/56404616-3a0e1d80-629a-11e9-98be-b68dbd631121.png)

**期望的结果 Expected behavior**
无论何时都能实时更新elx-scroll_bottom-pace的height属性

**请填写以下版本信息 please complete the following information**
 - vue: v2.6.10
 - element-ui: v2.7.2
 - vue-element-extends: v1.2.3

**Comment by xuliangzhan** [comment]
你可以更新到 1.2.4，修复了该问题 https://jsfiddle.net/w0x83gz1/

**Comment by ynzion** [comment]
> 你可以更新到 1.2.4，修复了该问题 https://jsfiddle.net/w0x83gz1/

谢谢您
