### ISSUE TITLE
調用insertAt遇到的問題

### ISSUE THREAD

**Issue by yangwb1123** [xuliangzhan/vue-element-extends#75]
**描述 Describe**

1、只能插入到第一行或者最後一行。
2、給第一個參數賦值，新增行後只能在 input 裡看到數據，跳出去就不顯示了，這個是一個星期前的版本。

**请填写以下版本信息 please complete the following information**
vue: v2.6.10
element-ui: v2.7.2
vue-element-extends: v1.2.3

**Comment by xuliangzhan** [comment]
你应该提供可重现问题的链接，描述不清楚

**Comment by yangwb1123** [comment]
@xuliangzhan 你好，这个是链接 https://jsrun.net/utXKp/edit

**Comment by xuliangzhan** [comment]
insertAt | 第二个参数 row 从指定位置新增一条数据； null 从第一行新增一行新数据；-1 从最后新增一条数据 | data,row
-- | -- | --


```
<el-button @click="$refs.editable.insertAt({text: 'Content'})">
        New at first line
      </el-button>
      <el-button @click="$refs.editable.insertAt({text: 'Content'}, tableData[1])">
        New at second line
      </el-button>
      <el-button @click="$refs.editable.insertAt({text: 'Content'}, -1)">
        New at last line
      </el-button>
```

**Comment by yangwb1123** [comment]
@xuliangzhan 谢谢了，能提下keydown事件的需求吗？

**Comment by xuliangzhan** [comment]
哪里的事件？

**Comment by yangwb1123** [comment]
就是键盘快捷键：
在编辑的时候，按下 Enter 退出编辑在原位置，按下 Esc 可以取消修改并退出在原位置，因为领导想基于这个vue-element-extends做一个键盘快捷键的插件所以如果能够自定义（增加行、删除行）快捷键就好了

**Comment by xuliangzhan** [comment]
更新到1.2.7 可以支持 keydownMethod 方法；你可以参考 [excel5](https://xuliangzhan.github.io/vue-element-extends/#/editable/excel5)

**Comment by yangwb1123** [comment]
@xuliangzhan 已經更新了，非常感謝
