### ISSUE TITLE
ElCascader将后台返回的值显示出来，并且在编辑的时候显示初始值

### ISSUE THREAD

**Issue by lnlnln123** [xuliangzhan/vue-element-extends#76]
**后台范湖是实时还是定时可以显示，但是在编辑的时候显示初始值**
![image](https://user-images.githubusercontent.com/25141771/56494537-2d512a00-6525-11e9-9c6b-f01de620bccb.png)

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**
https://jsrun.net/zTXKp/edit

**请填写以下版本信息 please complete the following information**
vue: 2.6.6?
element-ui:2.6.1 ?

**Comment by xuliangzhan** [comment]
你应该提供可重现问题的链接，描述不清楚

**Comment by lnlnln123** [comment]
后台会有一个关于这个用户是实时还是固定时间的一个返回值，需要将这个值显示在类型这一列，但是用户在点击修改这一列的时候，他的可选项是我写在代码里面的固定值。比如，这个用户是陕西省西安市的（这是后台返回的值，得一开始就显示出来），但是用户在点击修改的时候他的可选项依然是全国各省各市
