### ISSUE TITLE
xe-utils和vue-element-extends有版本依赖？

### ISSUE THREAD

**Issue by snowdream** [xuliangzhan/vue-element-extends#78]
**描述 Describe**
升级vue-element-extends到最新版本
xe-utils版本不动

更新 elx-editable
更新 elx-editable-column 

表格无法展示。
因此怀疑，xe-utils和vue-element-extends有版本依赖？
即xe-utils和vue-element-extends 的版本必须配合使用，相差太大，无法一起使用。

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**请填写以下版本信息 please complete the following information**
vue: ? .6.9
element-ui: ? 2.4.6
vue-element-extends: ? 1.2.6

**Comment by xuliangzhan** [comment]
是的，需要一起更新
npm install xe-utils vue-element-extends

**Comment by snowdream** [comment]
最好能给开发者提示一下，免得遇到莫名其妙的问题。
