### ISSUE TITLE
vue-element-extends表格内字体大小如何修改。

### ISSUE THREAD

**Issue by snowdream** [xuliangzhan/vue-element-extends#79]
**描述 Describe**
vue-element-extends升级到最新版后，发现表格内字体变大了。

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**请填写以下版本信息 please complete the following information**
vue: ? .6.9
element-ui: ? 2.4.6
vue-element-extends: ? 1.2.6

**Comment by xuliangzhan** [comment]
你说的是表格 size 吧，如果不指定默认是大的；
elementui全局参数设置 https://element.eleme.cn/#/zh-CN/component/quickstart

**Comment by snowdream** [comment]
加      size="mini"
表格内的字体和以前一样。
