### ISSUE TITLE
table不设高度，只有一行，校验错误信息显示不出来

### ISSUE THREAD

**Issue by dolphinfine** [xuliangzhan/vue-element-extends#8]
![image](https://user-images.githubusercontent.com/27426130/52909958-830e1980-32cb-11e9-9c21-025c0fee9507.png)

**Comment by xuliangzhan** [comment]
由于 Eltable 的容器设置了 overflow: hidden; 
解决方式：
1.设置2条数据以上的高度
2.把提示信息内容插入到容器外部

**Comment by dolphinfine** [comment]
谢谢。我还是给table设置了高度。
