### ISSUE TITLE
excell数据渲染改变列

### ISSUE THREAD

**Issue by wangjun043179** [xuliangzhan/vue-element-extends#80]
你好，我这边默认显示excell5列从A-E，但是我通过左边的菜单按钮追加几列后，我需要添加大于5列的数据，比如我需要添加7列数据，然后我后期得到这些数据需要渲染到表格，但是表格只有5列，我怎么通过我数据的长度去改变表格显示的列数呢？
下面这是我默认显示的列数
![123](https://user-images.githubusercontent.com/44045271/56575083-75408180-65f7-11e9-9384-2d0e76ca5267.png)
下面这是我5列的代码显示
![456](https://user-images.githubusercontent.com/44045271/56575123-8d180580-65f7-11e9-98b2-07719d942aa9.png)

**Comment by xuliangzhan** [comment]
你应该提供可重现问题的链接，描述不清楚
