### ISSUE TITLE
exportCsv设置参数

### ISSUE THREAD

**Issue by geekyzk** [xuliangzhan/vue-element-extends#81]
**描述 Describe**

使用导出CSV时，不知道如何设置导出得文件名以及列名称

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

无
**请填写以下版本信息 please complete the following information**
vue:  2.6.10
element-ui: 2.x
vue-element-extends: 1.X

**Comment by xuliangzhan** [comment]
属性 | 描述 | 类型 | 可选值 | 默认值
-- | -- | -- | -- | --
filename | 文件名 | String | — | table.csv
original | 是否导出源数据 | Boolean | — | false
data | 自定义数据 | Array | — | —
columns | 自定义列 | Array | — | —
columnFilterMethod | 列过滤方法，该函数 Function(row,index,list) 的返回值用来决定该列是否导出 | Function | — | —
dataFilterMethod | 数据过滤方法，该函数 Function(row,index,list) 的返回值用来决定该数据是否导出 | Function | — | —

**Comment by geekyzk** [comment]
多谢
