### ISSUE TITLE
context-menu-config是否支持自定义事件？

### ISSUE THREAD

**Issue by geekyzk** [xuliangzhan/vue-element-extends#82]
**描述 Describe**

查看context-menu-config配置参数，没看到支持自定义事件的，是否是只支持内置写好的code？
**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**
无

**请填写以下版本信息 please complete the following information**
vue: 2.6.10
element-ui: 2.7.x
vue-element-extends: 1.2.6

**Comment by xuliangzhan** [comment]
可以通过自定义 code 配合 custom-menu-link 事件就行，参考[excel5](https://xuliangzhan.github.io/vue-element-extends/#/editable/excel5)
