### ISSUE TITLE
tool.js hasClass 与 font-awesome-icon有冲突

### ISSUE THREAD

**Issue by sylaryip** [xuliangzhan/vue-element-extends#83]
**问题描述 Describe the bug**
 
使用font-awesome-icon时做button的图标时， 点击到 icon时 触发了_triggerClear事件中hasClass,
由于 SVGAnimatedString 没有 split方法导致出现错误

**重现问题的步骤 To Reproduce**

点击el-button上面的font-awesome-icon

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**报错信息或截图 Error message or screenshots**
![image](https://user-images.githubusercontent.com/46026135/56725572-b2d01680-677f-11e9-9909-e84da68aa6c6.png)

**期望的结果 Expected behavior**

**请填写以下版本信息 please complete the follo?wing information**
 - vue: 2.6.10
 - element-ui: ?2.7.2
 - vue-element-extends: ? 1.2.7

**Comment by xuliangzhan** [comment]
你可以更新到1.2.8+试下

**Comment by sylaryip** [comment]
问题解决，感谢
