### ISSUE TITLE
在開啟方向鍵和Tab鍵切換時按下方向鍵或者Tab鍵Table的currentRow未同步

### ISSUE THREAD

**Issue by yangwb1123** [xuliangzhan/vue-element-extends#84]
**描述 Describe**
開啟方向鍵、Tab鍵切換和高亮行，按下方向鍵或者Tab鍵使當前行發生變化時，高亮行沒有同步，即當前行未响应，當前行的數據沒有變化

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**请填写以下版本信息 please complete the following information**
vue: v2.6.10
element-ui: v2.7.2
vue-element-extends: v1.2.8

**Comment by xuliangzhan** [comment]
你应该提供可重现问题的链接，描述不太清楚

**Comment by yangwb1123** [comment]
@xuliangzhan 这个是链接http://jsrun.net/pjXKp/edit

![image](https://user-images.githubusercontent.com/43594478/56874882-86621600-6a6f-11e9-9f95-33d7700005f7.png)

按下ArrowDown，改变当前行没变化

![vue-element-extends@1 2 8 - WEB源jscssH5 - JSRUN - Google Chrome_2](https://user-images.githubusercontent.com/43594478/56875023-9c240b00-6a70-11e9-94eb-08dca055a379.png)

**Comment by xuliangzhan** [comment]
你可以更新到 1.2.10 试下

**Comment by yangwb1123** [comment]
@xuliangzhan 已更新到1.2.10版本 ArrowDown和ArrowUp键是可以了，Tab跳到下一行还没有，另外highlight-current-row未同步

**Comment by yangwb1123** [comment]
@xuliangzhan 已经更新版本，谢谢了
