### ISSUE TITLE
我用的1.0.6的版本，但是代码被别人拉走后却出了错

### ISSUE THREAD

**Issue by wsosw** [xuliangzhan/vue-element-extends#86]
本来用的是1.0.6的版本，在自己的电脑上没有问题，但是代码被别人拉走后，用到vue-element-extends的页面都出现了这个错误，请问这是什么原因导致的？
我试过更新vue的版本和vue-element-extends的版本，但是错误依旧存在，之后我又用2.6.10版本的vue，和1.0.6版本的vue-element-extends，但是错误依旧没有消除
[Vue warn]: Unknown custom element: <el-editable> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

版本
vue: 2.6.10
element-ui: 2.4.1
vue-element-extends: 1.0.6

**Comment by xuliangzhan** [comment]
你这提供报错信息不全
