### ISSUE TITLE
表头中editIcon以及required未渲染

### ISSUE THREAD

**Issue by xh4703** [xuliangzhan/vue-element-extends#87]
**描述 Describe**
表头中editIcon以及required未渲染

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**
直接拷贝code example中的Manual3代码测试的

**请填写以下版本信息 please complete the following information**
vue: 2.6.10
element-ui: 2.7.2?
vue-element-extends: 1.2.8?

**Comment by xuliangzhan** [comment]
你应该提供可重现问题的链接，描述不太清楚
