### ISSUE TITLE
数据多的时候

### ISSUE THREAD

**Issue by zibuyu1** [xuliangzhan/vue-element-extends#88]
当数据有几百上千条时卡死，操作缓慢，反应严重迟钝

**Comment by xuliangzhan** [comment]
elementui的表格本身就无法支撑大数据，再加上封装后的额外消耗
该组件不适用于一次性显示大量数据的表格，你可以使用滚动渲染 + renderSize  试下，缺点是会影响滚动体验。

**Comment by xuliangzhan** [comment]
虚拟滚动可以解决大数据量 https://xuliangzhan_admin.gitee.io/vxe-table/#/table/scroll/scroll
