### ISSUE TITLE
滚动渲染时怎么导出全部数据。

### ISSUE THREAD

**Issue by ghost** [xuliangzhan/vue-element-extends#89]
**描述 Describe**
我这里的需求有一千多条数据，所以使用了滚动渲染，但是用csv导出时，只包含了渲染后的数据。

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**请填写以下版本信息 please complete the following information**
vue: 2.6.6
element-ui: 2.7.0
vue-element-extends: 1.2.8

**Comment by xuliangzhan** [comment]
滚动渲染如果需要导出完整数据，需要转换数据源 参考[scroll](https://xuliangzhan.github.io/vue-element-extends/#/editable/scroll5/30000)

**Comment by ghost** [comment]
谢谢 已解决。
