### ISSUE TITLE
elx-editable default-sort lost

### ISSUE THREAD

**Issue by hacker0817** [xuliangzhan/vue-element-extends#90]
**描述 Describe**
i set default-sort，it first worked, but when i modify the bind array, the sort lost

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**请填写以下版本信息 please complete the following information**
vue: ?
element-ui: ?
vue-element-extends: ?

**Comment by hacker0817** [comment]
我开始设置了default-sort值，有效果，但是当我绑定数组做删除或修改时后，排序就丢失了

**Comment by xuliangzhan** [comment]
你可以更新到 1.2.12 试下
