### ISSUE TITLE
表格内级联如何实现

### ISSUE THREAD

**Issue by wangchangjie** [xuliangzhan/vue-element-extends#91]
当选择某个单元格数据，其他单元格默认填写数据，该如何实现

**Comment by liyuchuan86** [comment]
请问能实现编辑某个单元格时，联动另外一个加载数据吗？

**Comment by xuliangzhan** [comment]
这个不太明白想要实现什么，你可以在@change事件或者编辑失焦@blur-active之后去做处理

**Comment by liyuchuan86** [comment]
例如 有2列，列1为类型A，列2为B 选择类型A1的时候 B的选择项为B1,B2，选择A2的时候B的选择项为B3，B4，新增行的时候B的数据清空，重复这个操作，选择某一行的时候不影响其他行的选择，不知道我说清除没有

**Comment by sunzj1989** [comment]
> 当选择某个单元格数据，其他单元格默认填写数据，该如何实现

请问实现了吗？

**Comment by xuliangzhan** [comment]
通过列的change 事件不行了？
