### ISSUE TITLE
您好,在Excel模式下,能否支持同时选择多个单元格? 和 键盘的CTRL+C 和 CTRL+V 操作?

### ISSUE THREAD

**Issue by Jia4tin** [xuliangzhan/vue-element-extends#92]
您好,在Excel模式下,能否支持同时选择多个单元格? 和 键盘的CTRL+C 和 CTRL+V 操作?

**Comment by xuliangzhan** [comment]
这个是基于 element 的无法实现这种功能，后续会在 [vxe-table](https://xuliangzhan.github.io/vxe-table/)  支持该功能
