### ISSUE TITLE
ElCascader显示最后一级

### ISSUE THREAD

**Issue by zerozrn** [xuliangzhan/vue-element-extends#93]
**描述 Describe**
ElCascader如何设置显示最后一级?不想显示完整路径，用了element-ui的方法无效.
![QQ截图20190505161522](https://user-images.githubusercontent.com/19562124/57190815-5aec9900-6f51-11e9-981d-a42411e17e1e.png)
就像这样的

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**请填写以下版本信息 please complete the following information**
vue: 2.5.2
element-ui: 2.4.11
vue-element-extends: 1.2.13

**Comment by xuliangzhan** [comment]
你可以更新到最新试下

**Comment by zerozrn** [comment]
如何在编辑状态,给渲染的ElCascader添加change事件?
vue-element-extends: 1.2.15

**Comment by xuliangzhan** [comment]
参数可以参考这个 #104

**Comment by zerozrn** [comment]
非常感谢，我认真看了您的demo发现答案了，谢谢，当时没有太多时间才提的问题，感谢解答
