### ISSUE TITLE
自定义组件获取焦点问题？

### ISSUE THREAD

**Issue by chenyinlong** [xuliangzhan/vue-element-extends#94]
**描述 Describe**

自定义组件获取焦点问题？

所有自定义组件都无法自动获取焦点？

**请填写以下版本信息 please complete the following information**
vue: 2.6.10
element-ui: 2.8.2
vue-element-extends: 1.2.14

**Comment by xuliangzhan** [comment]
你应该提供可重现问题的链接

**Comment by chenyinlong** [comment]
@xuliangzhan 
问题解决了，用
`this.$refs.elxEditable
        .insertAt(
          {
            name: ``,
            ref: "new"
          },
          this.yaoTableData.length
        )
        .then(data => {
          this.$refs.elxEditable.setActiveRow(data.row);
          this.timer = setTimeout(() => {
            window.document
              .querySelector(".el-autocomplete .el-input__inner")
              .focus();
          });
        });`

当setActiveRow 使一行变为可编辑状态时，在 setTimeOut 内 使用 查询到dom元素，能获取到元素并获取焦点

**Comment by xuliangzhan** [comment]
其实你可以设置 :edit-render="{name: 'ElAutocomplete'}" 配合自定义渲染也是可以自动获取焦点的
