### ISSUE TITLE
序号列label不起作用，写死了#？

### ISSUE THREAD

**Issue by agileago** [xuliangzhan/vue-element-extends#95]
**问题描述 Describe the bug**

序号列的`label`属性不起作用，在原`element`里面是生效的
**重现问题的步骤 To Reproduce**

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**
`lable`属性生效

**请填写以下版本信息 please complete the following information**
 - vue: ?
 - element-ui: ?
 - vue-element-extends: ?

**Comment by xuliangzhan** [comment]
你可以更新试下
