### ISSUE TITLE
必填列的表头的*星号可以隐藏吗

### ISSUE THREAD

**Issue by owen4comes** [xuliangzhan/vue-element-extends#96]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能 Is your feature request related to a problem? Please describe.**
需求是表头保持整洁，即使是必填列也不需要显示必填的*星号

**描述下，你希望得到的什么解决方案 Describe the solution you'd like**
希望每列有一个开关参数可以隐藏

**是否有不错的替代方案 Describe alternatives you've considered**
暂时没有谢谢

**Comment by xuliangzhan** [comment]
如果某列可以通过slot header去自定义模板
如果是全部不需要，通过样式隐藏就行

**Comment by owen4comes** [comment]
好的谢谢
