### ISSUE TITLE
elx-editable 中树形默认全展开或者展开一级通过defaultExpandAll或者expand-row-keys设置都不生效

### ISSUE THREAD

**Issue by kairui081011** [xuliangzhan/vue-element-extends#97]
**问题描述 Describe the bug**
表格中树形展示时，默认要全展开所有行，目前提供的属性方法不生效

**重现问题的步骤 To Reproduce**
样例上给出树形全展开的实例即可

**请提供能重现问题的链接（jsfiddle、jsrun） Expected behavior**

**报错信息或截图 Error message or screenshots**

**期望的结果 Expected behavior**
树形全展开

**请填写以下版本信息 please complete the following information**
 - vue: ?
 - element-ui: ?
 - vue-element-extends: ?

**Comment by xuliangzhan** [comment]
你应该先确定参数在 element 上可行才能用在 elx-editable
