### ISSUE TITLE
excell表格列字段支不支持排序

### ISSUE THREAD

**Issue by wangjun043179** [xuliangzhan/vue-element-extends#99]
你好，我想问下，excell表格支持排序功能吗？我看上面是按条件筛选，我想做排序功能

**Comment by wangjun043179** [comment]
![TIM截图20190510103311](https://user-images.githubusercontent.com/44045271/57498709-97344680-730f-11e9-91f1-7a6c46903245.png)

**Comment by wangjun043179** [comment]
![TIM截图20190510103707](https://user-images.githubusercontent.com/44045271/57498719-9f8c8180-730f-11e9-8a2e-58b938ba03da.png)

**Comment by xuliangzhan** [comment]
你应该看 element-ui 的文档，可以支持的
